"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getClusterOutput = exports.getCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Provides details about a specific redshift cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.redshift.getCluster({
 *     clusterIdentifier: "example-cluster",
 * });
 * const exampleStream = new aws.kinesis.FirehoseDeliveryStream("example_stream", {
 *     name: "kinesis-firehose-example-stream",
 *     destination: "redshift",
 *     redshiftConfiguration: {
 *         roleArn: firehoseRole.arn,
 *         clusterJdbcurl: Promise.all([example, example]).then(([example, example1]) => `jdbc:redshift://${example.endpoint}/${example1.databaseName}`),
 *         username: "exampleuser",
 *         password: "Exampl3Pass",
 *         dataTableName: "example-table",
 *         copyOptions: "delimiter '|'",
 *         dataTableColumns: "example-col",
 *         s3Configuration: {
 *             roleArn: firehoseRole.arn,
 *             bucketArn: bucket.arn,
 *             bufferSize: 10,
 *             bufferInterval: 400,
 *             compressionFormat: "GZIP",
 *         },
 *     },
 * });
 * ```
 */
function getCluster(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:redshift/getCluster:getCluster", {
        "clusterIdentifier": args.clusterIdentifier,
        "region": args.region,
        "tags": args.tags,
    }, opts);
}
exports.getCluster = getCluster;
/**
 * Provides details about a specific redshift cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.redshift.getCluster({
 *     clusterIdentifier: "example-cluster",
 * });
 * const exampleStream = new aws.kinesis.FirehoseDeliveryStream("example_stream", {
 *     name: "kinesis-firehose-example-stream",
 *     destination: "redshift",
 *     redshiftConfiguration: {
 *         roleArn: firehoseRole.arn,
 *         clusterJdbcurl: Promise.all([example, example]).then(([example, example1]) => `jdbc:redshift://${example.endpoint}/${example1.databaseName}`),
 *         username: "exampleuser",
 *         password: "Exampl3Pass",
 *         dataTableName: "example-table",
 *         copyOptions: "delimiter '|'",
 *         dataTableColumns: "example-col",
 *         s3Configuration: {
 *             roleArn: firehoseRole.arn,
 *             bucketArn: bucket.arn,
 *             bufferSize: 10,
 *             bufferInterval: 400,
 *             compressionFormat: "GZIP",
 *         },
 *     },
 * });
 * ```
 */
function getClusterOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:redshift/getCluster:getCluster", {
        "clusterIdentifier": args.clusterIdentifier,
        "region": args.region,
        "tags": args.tags,
    }, opts);
}
exports.getClusterOutput = getClusterOutput;
//# sourceMappingURL=getCluster.js.map