"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.LfTagExpression = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Resource for managing an AWS Lake Formation LF Tag Expression.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = new aws.lakeformation.LfTag("example", {
 *     key: "example",
 *     values: ["value"],
 * });
 * const exampleLfTagExpression = new aws.lakeformation.LfTagExpression("example", {
 *     name: "example",
 *     expressions: [{
 *         tagKey: example.key,
 *         tagValues: example.values,
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import Lake Formation LF Tag Expression using the `name,catalog_id`. For example:
 *
 * ```sh
 * $ pulumi import aws:lakeformation/lfTagExpression:LfTagExpression example example-tag-expression,123456789012
 * ```
 */
class LfTagExpression extends pulumi.CustomResource {
    /**
     * Get an existing LfTagExpression resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new LfTagExpression(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of LfTagExpression.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LfTagExpression.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["catalogId"] = state?.catalogId;
            resourceInputs["description"] = state?.description;
            resourceInputs["expressions"] = state?.expressions;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
        }
        else {
            const args = argsOrState;
            resourceInputs["catalogId"] = args?.catalogId;
            resourceInputs["description"] = args?.description;
            resourceInputs["expressions"] = args?.expressions;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LfTagExpression.__pulumiType, name, resourceInputs, opts);
    }
}
exports.LfTagExpression = LfTagExpression;
/** @internal */
LfTagExpression.__pulumiType = 'aws:lakeformation/lfTagExpression:LfTagExpression';
//# sourceMappingURL=lfTagExpression.js.map