export { GetAuthorizationTokenArgs, GetAuthorizationTokenResult, GetAuthorizationTokenOutputArgs } from "./getAuthorizationToken";
export declare const getAuthorizationToken: typeof import("./getAuthorizationToken").getAuthorizationToken;
export declare const getAuthorizationTokenOutput: typeof import("./getAuthorizationToken").getAuthorizationTokenOutput;
export { GetImagesArgs, GetImagesResult, GetImagesOutputArgs } from "./getImages";
export declare const getImages: typeof import("./getImages").getImages;
export declare const getImagesOutput: typeof import("./getImages").getImagesOutput;
export { RepositoryArgs, RepositoryState } from "./repository";
export type Repository = import("./repository").Repository;
export declare const Repository: typeof import("./repository").Repository;
export { RepositoryPolicyArgs, RepositoryPolicyState } from "./repositoryPolicy";
export type RepositoryPolicy = import("./repositoryPolicy").RepositoryPolicy;
export declare const RepositoryPolicy: typeof import("./repositoryPolicy").RepositoryPolicy;
