"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getImagesOutput = exports.getImages = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * The ECR Public Images data source allows the list of images in a specified public repository to be retrieved.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const example = aws.ecrpublic.getImages({
 *     repositoryName: "my-public-repository",
 * });
 * export const imageDigests = example.then(example => .filter(img => img.digest != null).map(img => (img.digest)));
 * export const imageTags = example.then(example => std.flatten({
 *     input: .map(img => (img.tags)),
 * })).then(invoke => std.distinct({
 *     input: invoke.result,
 * })).then(invoke => invoke.result);
 * ```
 */
function getImages(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:ecrpublic/getImages:getImages", {
        "imageIds": args.imageIds,
        "region": args.region,
        "registryId": args.registryId,
        "repositoryName": args.repositoryName,
    }, opts);
}
exports.getImages = getImages;
/**
 * The ECR Public Images data source allows the list of images in a specified public repository to be retrieved.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const example = aws.ecrpublic.getImages({
 *     repositoryName: "my-public-repository",
 * });
 * export const imageDigests = example.then(example => .filter(img => img.digest != null).map(img => (img.digest)));
 * export const imageTags = example.then(example => std.flatten({
 *     input: .map(img => (img.tags)),
 * })).then(invoke => std.distinct({
 *     input: invoke.result,
 * })).then(invoke => invoke.result);
 * ```
 */
function getImagesOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:ecrpublic/getImages:getImages", {
        "imageIds": args.imageIds,
        "region": args.region,
        "registryId": args.registryId,
        "repositoryName": args.repositoryName,
    }, opts);
}
exports.getImagesOutput = getImagesOutput;
//# sourceMappingURL=getImages.js.map