"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCloudVmClustersOutput = exports.getCloudVmClusters = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for retrieving all cloud vm clusters AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudVmClusters({});
 * ```
 */
function getCloudVmClusters(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getCloudVmClusters:getCloudVmClusters", {
        "region": args.region,
    }, opts);
}
exports.getCloudVmClusters = getCloudVmClusters;
/**
 * Data source for retrieving all cloud vm clusters AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudVmClusters({});
 * ```
 */
function getCloudVmClustersOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getCloudVmClusters:getCloudVmClusters", {
        "region": args.region,
    }, opts);
}
exports.getCloudVmClustersOutput = getCloudVmClustersOutput;
//# sourceMappingURL=getCloudVmClusters.js.map