export { CloudAutonomousVmClusterArgs, CloudAutonomousVmClusterState } from "./cloudAutonomousVmCluster";
export type CloudAutonomousVmCluster = import("./cloudAutonomousVmCluster").CloudAutonomousVmCluster;
export declare const CloudAutonomousVmCluster: typeof import("./cloudAutonomousVmCluster").CloudAutonomousVmCluster;
export { CloudExadataInfrastructureArgs, CloudExadataInfrastructureState } from "./cloudExadataInfrastructure";
export type CloudExadataInfrastructure = import("./cloudExadataInfrastructure").CloudExadataInfrastructure;
export declare const CloudExadataInfrastructure: typeof import("./cloudExadataInfrastructure").CloudExadataInfrastructure;
export { CloudVmClusterArgs, CloudVmClusterState } from "./cloudVmCluster";
export type CloudVmCluster = import("./cloudVmCluster").CloudVmCluster;
export declare const CloudVmCluster: typeof import("./cloudVmCluster").CloudVmCluster;
export { GetCloudAutonomousVmClusterArgs, GetCloudAutonomousVmClusterResult, GetCloudAutonomousVmClusterOutputArgs } from "./getCloudAutonomousVmCluster";
export declare const getCloudAutonomousVmCluster: typeof import("./getCloudAutonomousVmCluster").getCloudAutonomousVmCluster;
export declare const getCloudAutonomousVmClusterOutput: typeof import("./getCloudAutonomousVmCluster").getCloudAutonomousVmClusterOutput;
export { GetCloudAutonomousVmClustersArgs, GetCloudAutonomousVmClustersResult, GetCloudAutonomousVmClustersOutputArgs } from "./getCloudAutonomousVmClusters";
export declare const getCloudAutonomousVmClusters: typeof import("./getCloudAutonomousVmClusters").getCloudAutonomousVmClusters;
export declare const getCloudAutonomousVmClustersOutput: typeof import("./getCloudAutonomousVmClusters").getCloudAutonomousVmClustersOutput;
export { GetCloudExadataInfrastructureArgs, GetCloudExadataInfrastructureResult, GetCloudExadataInfrastructureOutputArgs } from "./getCloudExadataInfrastructure";
export declare const getCloudExadataInfrastructure: typeof import("./getCloudExadataInfrastructure").getCloudExadataInfrastructure;
export declare const getCloudExadataInfrastructureOutput: typeof import("./getCloudExadataInfrastructure").getCloudExadataInfrastructureOutput;
export { GetCloudExadataInfrastructuresArgs, GetCloudExadataInfrastructuresResult, GetCloudExadataInfrastructuresOutputArgs } from "./getCloudExadataInfrastructures";
export declare const getCloudExadataInfrastructures: typeof import("./getCloudExadataInfrastructures").getCloudExadataInfrastructures;
export declare const getCloudExadataInfrastructuresOutput: typeof import("./getCloudExadataInfrastructures").getCloudExadataInfrastructuresOutput;
export { GetCloudVmClusterArgs, GetCloudVmClusterResult, GetCloudVmClusterOutputArgs } from "./getCloudVmCluster";
export declare const getCloudVmCluster: typeof import("./getCloudVmCluster").getCloudVmCluster;
export declare const getCloudVmClusterOutput: typeof import("./getCloudVmCluster").getCloudVmClusterOutput;
export { GetCloudVmClustersArgs, GetCloudVmClustersResult, GetCloudVmClustersOutputArgs } from "./getCloudVmClusters";
export declare const getCloudVmClusters: typeof import("./getCloudVmClusters").getCloudVmClusters;
export declare const getCloudVmClustersOutput: typeof import("./getCloudVmClusters").getCloudVmClustersOutput;
export { GetDbNodeArgs, GetDbNodeResult, GetDbNodeOutputArgs } from "./getDbNode";
export declare const getDbNode: typeof import("./getDbNode").getDbNode;
export declare const getDbNodeOutput: typeof import("./getDbNode").getDbNodeOutput;
export { GetDbNodesArgs, GetDbNodesResult, GetDbNodesOutputArgs } from "./getDbNodes";
export declare const getDbNodes: typeof import("./getDbNodes").getDbNodes;
export declare const getDbNodesOutput: typeof import("./getDbNodes").getDbNodesOutput;
export { GetDbServerArgs, GetDbServerResult, GetDbServerOutputArgs } from "./getDbServer";
export declare const getDbServer: typeof import("./getDbServer").getDbServer;
export declare const getDbServerOutput: typeof import("./getDbServer").getDbServerOutput;
export { GetDbServersArgs, GetDbServersResult, GetDbServersOutputArgs } from "./getDbServers";
export declare const getDbServers: typeof import("./getDbServers").getDbServers;
export declare const getDbServersOutput: typeof import("./getDbServers").getDbServersOutput;
export { GetDbSystemShapesArgs, GetDbSystemShapesResult, GetDbSystemShapesOutputArgs } from "./getDbSystemShapes";
export declare const getDbSystemShapes: typeof import("./getDbSystemShapes").getDbSystemShapes;
export declare const getDbSystemShapesOutput: typeof import("./getDbSystemShapes").getDbSystemShapesOutput;
export { GetGiVersionsArgs, GetGiVersionsResult, GetGiVersionsOutputArgs } from "./getGiVersions";
export declare const getGiVersions: typeof import("./getGiVersions").getGiVersions;
export declare const getGiVersionsOutput: typeof import("./getGiVersions").getGiVersionsOutput;
export { GetNetworkArgs, GetNetworkResult, GetNetworkOutputArgs } from "./getNetwork";
export declare const getNetwork: typeof import("./getNetwork").getNetwork;
export declare const getNetworkOutput: typeof import("./getNetwork").getNetworkOutput;
export { GetNetworkPeeringConnectionArgs, GetNetworkPeeringConnectionResult, GetNetworkPeeringConnectionOutputArgs } from "./getNetworkPeeringConnection";
export declare const getNetworkPeeringConnection: typeof import("./getNetworkPeeringConnection").getNetworkPeeringConnection;
export declare const getNetworkPeeringConnectionOutput: typeof import("./getNetworkPeeringConnection").getNetworkPeeringConnectionOutput;
export { GetNetworkPeeringConnectionsArgs, GetNetworkPeeringConnectionsResult, GetNetworkPeeringConnectionsOutputArgs } from "./getNetworkPeeringConnections";
export declare const getNetworkPeeringConnections: typeof import("./getNetworkPeeringConnections").getNetworkPeeringConnections;
export declare const getNetworkPeeringConnectionsOutput: typeof import("./getNetworkPeeringConnections").getNetworkPeeringConnectionsOutput;
export { GetNetworksArgs, GetNetworksResult, GetNetworksOutputArgs } from "./getNetworks";
export declare const getNetworks: typeof import("./getNetworks").getNetworks;
export declare const getNetworksOutput: typeof import("./getNetworks").getNetworksOutput;
export { NetworkArgs, NetworkState } from "./network";
export type Network = import("./network").Network;
export declare const Network: typeof import("./network").Network;
export { NetworkPeeringConnectionArgs, NetworkPeeringConnectionState } from "./networkPeeringConnection";
export type NetworkPeeringConnection = import("./networkPeeringConnection").NetworkPeeringConnection;
export declare const NetworkPeeringConnection: typeof import("./networkPeeringConnection").NetworkPeeringConnection;
