"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.InvoiceUnit = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages an AWS Invoice Unit for organizational billing.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = new aws.invoicing.InvoiceUnit("example", {
 *     name: "example-unit",
 *     description: "Example invoice unit",
 *     invoiceReceiver: "123456789012",
 *     rules: [{
 *         linkedAccounts: ["098765432109"],
 *     }],
 *     tags: {
 *         Environment: "production",
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import Invoice Units using the ARN. For example:
 *
 * ```sh
 * $ pulumi import aws:invoicing/invoiceUnit:InvoiceUnit example arn:aws:invoicing::123456789012:invoice-unit/example-id
 * ```
 */
class InvoiceUnit extends pulumi.CustomResource {
    /**
     * Get an existing InvoiceUnit resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new InvoiceUnit(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of InvoiceUnit.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === InvoiceUnit.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["arn"] = state?.arn;
            resourceInputs["description"] = state?.description;
            resourceInputs["invoiceReceiver"] = state?.invoiceReceiver;
            resourceInputs["lastModified"] = state?.lastModified;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
            resourceInputs["rules"] = state?.rules;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tagsAll"] = state?.tagsAll;
            resourceInputs["taxInheritanceDisabled"] = state?.taxInheritanceDisabled;
            resourceInputs["timeouts"] = state?.timeouts;
        }
        else {
            const args = argsOrState;
            if (args?.invoiceReceiver === undefined && !opts.urn) {
                throw new Error("Missing required property 'invoiceReceiver'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["invoiceReceiver"] = args?.invoiceReceiver;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["rules"] = args?.rules;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["taxInheritanceDisabled"] = args?.taxInheritanceDisabled;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["lastModified"] = undefined /*out*/;
            resourceInputs["tagsAll"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(InvoiceUnit.__pulumiType, name, resourceInputs, opts);
    }
}
exports.InvoiceUnit = InvoiceUnit;
/** @internal */
InvoiceUnit.__pulumiType = 'aws:invoicing/invoiceUnit:InvoiceUnit';
//# sourceMappingURL=invoiceUnit.js.map