"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudExadataInfrastructure = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Resource for managing exadata infrastructure resource in AWS for Oracle Database@AWS.
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Using `pulumi import`, import Exadata Infrastructure using the `id`. For example:
 *
 * ```sh
 * $ pulumi import aws:odb/cloudExadataInfrastructure:CloudExadataInfrastructure example example
 * ```
 */
class CloudExadataInfrastructure extends pulumi.CustomResource {
    /**
     * Get an existing CloudExadataInfrastructure resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new CloudExadataInfrastructure(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of CloudExadataInfrastructure.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudExadataInfrastructure.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["activatedStorageCount"] = state?.activatedStorageCount;
            resourceInputs["additionalStorageCount"] = state?.additionalStorageCount;
            resourceInputs["arn"] = state?.arn;
            resourceInputs["availabilityZone"] = state?.availabilityZone;
            resourceInputs["availabilityZoneId"] = state?.availabilityZoneId;
            resourceInputs["availableStorageSizeInGbs"] = state?.availableStorageSizeInGbs;
            resourceInputs["computeCount"] = state?.computeCount;
            resourceInputs["computeModel"] = state?.computeModel;
            resourceInputs["cpuCount"] = state?.cpuCount;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["customerContactsToSendToOcis"] = state?.customerContactsToSendToOcis;
            resourceInputs["dataStorageSizeInTbs"] = state?.dataStorageSizeInTbs;
            resourceInputs["databaseServerType"] = state?.databaseServerType;
            resourceInputs["dbNodeStorageSizeInGbs"] = state?.dbNodeStorageSizeInGbs;
            resourceInputs["dbServerVersion"] = state?.dbServerVersion;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["lastMaintenanceRunId"] = state?.lastMaintenanceRunId;
            resourceInputs["maintenanceWindow"] = state?.maintenanceWindow;
            resourceInputs["maxCpuCount"] = state?.maxCpuCount;
            resourceInputs["maxDataStorageInTbs"] = state?.maxDataStorageInTbs;
            resourceInputs["maxDbNodeStorageSizeInGbs"] = state?.maxDbNodeStorageSizeInGbs;
            resourceInputs["maxMemoryInGbs"] = state?.maxMemoryInGbs;
            resourceInputs["memorySizeInGbs"] = state?.memorySizeInGbs;
            resourceInputs["monthlyDbServerVersion"] = state?.monthlyDbServerVersion;
            resourceInputs["monthlyStorageServerVersion"] = state?.monthlyStorageServerVersion;
            resourceInputs["nextMaintenanceRunId"] = state?.nextMaintenanceRunId;
            resourceInputs["ociResourceAnchorName"] = state?.ociResourceAnchorName;
            resourceInputs["ociUrl"] = state?.ociUrl;
            resourceInputs["ocid"] = state?.ocid;
            resourceInputs["percentProgress"] = state?.percentProgress;
            resourceInputs["region"] = state?.region;
            resourceInputs["shape"] = state?.shape;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusReason"] = state?.statusReason;
            resourceInputs["storageCount"] = state?.storageCount;
            resourceInputs["storageServerType"] = state?.storageServerType;
            resourceInputs["storageServerVersion"] = state?.storageServerVersion;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tagsAll"] = state?.tagsAll;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["totalStorageSizeInGbs"] = state?.totalStorageSizeInGbs;
        }
        else {
            const args = argsOrState;
            if (args?.availabilityZoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'availabilityZoneId'");
            }
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.shape === undefined && !opts.urn) {
                throw new Error("Missing required property 'shape'");
            }
            resourceInputs["availabilityZone"] = args?.availabilityZone;
            resourceInputs["availabilityZoneId"] = args?.availabilityZoneId;
            resourceInputs["computeCount"] = args?.computeCount;
            resourceInputs["customerContactsToSendToOcis"] = args?.customerContactsToSendToOcis;
            resourceInputs["databaseServerType"] = args?.databaseServerType;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["maintenanceWindow"] = args?.maintenanceWindow;
            resourceInputs["region"] = args?.region;
            resourceInputs["shape"] = args?.shape;
            resourceInputs["storageCount"] = args?.storageCount;
            resourceInputs["storageServerType"] = args?.storageServerType;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["activatedStorageCount"] = undefined /*out*/;
            resourceInputs["additionalStorageCount"] = undefined /*out*/;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["availableStorageSizeInGbs"] = undefined /*out*/;
            resourceInputs["computeModel"] = undefined /*out*/;
            resourceInputs["cpuCount"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["dataStorageSizeInTbs"] = undefined /*out*/;
            resourceInputs["dbNodeStorageSizeInGbs"] = undefined /*out*/;
            resourceInputs["dbServerVersion"] = undefined /*out*/;
            resourceInputs["lastMaintenanceRunId"] = undefined /*out*/;
            resourceInputs["maxCpuCount"] = undefined /*out*/;
            resourceInputs["maxDataStorageInTbs"] = undefined /*out*/;
            resourceInputs["maxDbNodeStorageSizeInGbs"] = undefined /*out*/;
            resourceInputs["maxMemoryInGbs"] = undefined /*out*/;
            resourceInputs["memorySizeInGbs"] = undefined /*out*/;
            resourceInputs["monthlyDbServerVersion"] = undefined /*out*/;
            resourceInputs["monthlyStorageServerVersion"] = undefined /*out*/;
            resourceInputs["nextMaintenanceRunId"] = undefined /*out*/;
            resourceInputs["ociResourceAnchorName"] = undefined /*out*/;
            resourceInputs["ociUrl"] = undefined /*out*/;
            resourceInputs["ocid"] = undefined /*out*/;
            resourceInputs["percentProgress"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["statusReason"] = undefined /*out*/;
            resourceInputs["storageServerVersion"] = undefined /*out*/;
            resourceInputs["tagsAll"] = undefined /*out*/;
            resourceInputs["totalStorageSizeInGbs"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudExadataInfrastructure.__pulumiType, name, resourceInputs, opts);
    }
}
exports.CloudExadataInfrastructure = CloudExadataInfrastructure;
/** @internal */
CloudExadataInfrastructure.__pulumiType = 'aws:odb/cloudExadataInfrastructure:CloudExadataInfrastructure';
//# sourceMappingURL=cloudExadataInfrastructure.js.map