"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getGiVersionsOutput = exports.getGiVersions = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source to retrieve available Grid Infrastructure versions of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 */
function getGiVersions(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getGiVersions:getGiVersions", {
        "region": args.region,
        "shape": args.shape,
    }, opts);
}
exports.getGiVersions = getGiVersions;
/**
 * Data source to retrieve available Grid Infrastructure versions of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 */
function getGiVersionsOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getGiVersions:getGiVersions", {
        "region": args.region,
        "shape": args.shape,
    }, opts);
}
exports.getGiVersionsOutput = getGiVersionsOutput;
//# sourceMappingURL=getGiVersions.js.map