"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getApplicationOutput = exports.getApplication = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Provides details about an AWS AppConfig Application.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.appconfig.getApplication({
 *     name: "my-appconfig-application",
 * });
 * ```
 */
function getApplication(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:appconfig/getApplication:getApplication", {
        "id": args.id,
        "name": args.name,
        "region": args.region,
    }, opts);
}
exports.getApplication = getApplication;
/**
 * Provides details about an AWS AppConfig Application.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.appconfig.getApplication({
 *     name: "my-appconfig-application",
 * });
 * ```
 */
function getApplicationOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:appconfig/getApplication:getApplication", {
        "id": args.id,
        "name": args.name,
        "region": args.region,
    }, opts);
}
exports.getApplicationOutput = getApplicationOutput;
//# sourceMappingURL=getApplication.js.map