"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getNetworkOutput = exports.getNetwork = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for to retrieve network resource in AWS for Oracle Database@AWS.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetwork({
 *     id: "example",
 * });
 * ```
 */
function getNetwork(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getNetwork:getNetwork", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getNetwork = getNetwork;
/**
 * Data source for to retrieve network resource in AWS for Oracle Database@AWS.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetwork({
 *     id: "example",
 * });
 * ```
 */
function getNetworkOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getNetwork:getNetwork", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getNetworkOutput = getNetworkOutput;
//# sourceMappingURL=getNetwork.js.map