"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getVpcAttachmentOutput = exports.getVpcAttachment = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Get information on an EC2 Transit Gateway VPC Attachment.
 *
 * !> **Warning:** Using the `aws.ec2transitgateway.VpcAttachment` data source in combination with  `aws.ec2transitgateway.RouteTablePropagation` or `aws.ec2transitgateway.RouteTableAssociation` may result in lost connectivity due to unnecessary resource re-creation. To avoid this, use the `id` attribute directly from the `aws.ec2transitgateway.VpcAttachment` _resource_. For example, `transitGatewayAttachmentId  = aws_ec2_transit_gateway_vpc_attachment.example.id`.
 *
 * ## Example Usage
 *
 * ### By Filter
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2transitgateway.getVpcAttachment({
 *     filters: [{
 *         name: "vpc-id",
 *         values: ["vpc-12345678"],
 *     }],
 * });
 * ```
 *
 * ### By Identifier
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2transitgateway.getVpcAttachment({
 *     id: "tgw-attach-12345678",
 * });
 * ```
 */
function getVpcAttachment(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:ec2transitgateway/getVpcAttachment:getVpcAttachment", {
        "filters": args.filters,
        "id": args.id,
        "region": args.region,
        "tags": args.tags,
    }, opts);
}
exports.getVpcAttachment = getVpcAttachment;
/**
 * Get information on an EC2 Transit Gateway VPC Attachment.
 *
 * !> **Warning:** Using the `aws.ec2transitgateway.VpcAttachment` data source in combination with  `aws.ec2transitgateway.RouteTablePropagation` or `aws.ec2transitgateway.RouteTableAssociation` may result in lost connectivity due to unnecessary resource re-creation. To avoid this, use the `id` attribute directly from the `aws.ec2transitgateway.VpcAttachment` _resource_. For example, `transitGatewayAttachmentId  = aws_ec2_transit_gateway_vpc_attachment.example.id`.
 *
 * ## Example Usage
 *
 * ### By Filter
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2transitgateway.getVpcAttachment({
 *     filters: [{
 *         name: "vpc-id",
 *         values: ["vpc-12345678"],
 *     }],
 * });
 * ```
 *
 * ### By Identifier
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2transitgateway.getVpcAttachment({
 *     id: "tgw-attach-12345678",
 * });
 * ```
 */
function getVpcAttachmentOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:ec2transitgateway/getVpcAttachment:getVpcAttachment", {
        "filters": args.filters,
        "id": args.id,
        "region": args.region,
        "tags": args.tags,
    }, opts);
}
exports.getVpcAttachmentOutput = getVpcAttachmentOutput;
//# sourceMappingURL=getVpcAttachment.js.map