"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.ManagedLoginBranding = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages branding settings for a user pool style and associates it with an app client.
 *
 * ## Example Usage
 *
 * ### Default Branding Style
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const client = new aws.cognito.ManagedLoginBranding("client", {
 *     clientId: example.id,
 *     userPoolId: exampleAwsCognitoUserPool.id,
 *     useCognitoProvidedValues: true,
 * });
 * ```
 *
 * ### Custom Branding Style
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const client = new aws.cognito.ManagedLoginBranding("client", {
 *     clientId: example.id,
 *     userPoolId: exampleAwsCognitoUserPool.id,
 *     assets: [{
 *         bytes: std.filebase64({
 *             input: "login_branding_asset.svg",
 *         }).then(invoke => invoke.result),
 *         category: "PAGE_HEADER_BACKGROUND",
 *         colorMode: "DARK",
 *         extension: "SVG",
 *     }],
 *     settings: JSON.stringify({}),
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import Cognito branding settings using `user_pool_id` and `managed_login_branding_id` separated by `,`. For example:
 *
 * ```sh
 * $ pulumi import aws:cognito/managedLoginBranding:ManagedLoginBranding example us-west-2_rSss9Zltr,06c6ae7b-1e66-46d2-87a9-1203ea3307bd
 * ```
 */
class ManagedLoginBranding extends pulumi.CustomResource {
    /**
     * Get an existing ManagedLoginBranding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new ManagedLoginBranding(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of ManagedLoginBranding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ManagedLoginBranding.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["assets"] = state?.assets;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["managedLoginBrandingId"] = state?.managedLoginBrandingId;
            resourceInputs["region"] = state?.region;
            resourceInputs["settings"] = state?.settings;
            resourceInputs["settingsAll"] = state?.settingsAll;
            resourceInputs["useCognitoProvidedValues"] = state?.useCognitoProvidedValues;
            resourceInputs["userPoolId"] = state?.userPoolId;
        }
        else {
            const args = argsOrState;
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.userPoolId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userPoolId'");
            }
            resourceInputs["assets"] = args?.assets;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["region"] = args?.region;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["useCognitoProvidedValues"] = args?.useCognitoProvidedValues;
            resourceInputs["userPoolId"] = args?.userPoolId;
            resourceInputs["managedLoginBrandingId"] = undefined /*out*/;
            resourceInputs["settingsAll"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ManagedLoginBranding.__pulumiType, name, resourceInputs, opts);
    }
}
exports.ManagedLoginBranding = ManagedLoginBranding;
/** @internal */
ManagedLoginBranding.__pulumiType = 'aws:cognito/managedLoginBranding:ManagedLoginBranding';
//# sourceMappingURL=managedLoginBranding.js.map