"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getPoliciesForTargetOutput = exports.getPoliciesForTarget = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for managing an AWS Organizations Policies For Target.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const example = aws.organizations.getOrganization({});
 * const exampleGetPoliciesForTarget = example.then(example => aws.organizations.getPoliciesForTarget({
 *     targetId: example.roots?.[0]?.id,
 *     filter: "SERVICE_CONTROL_POLICY",
 * }));
 * const exampleGetPolicy = exampleGetPoliciesForTarget.then(exampleGetPoliciesForTarget => std.toset({
 *     input: exampleGetPoliciesForTarget.ids,
 * })).then(invoke => .reduce((__obj, [__key, __value]) => ({ ...__obj, [__key]: aws.organizations.getPolicy({
 *     policyId: __value,
 * }) })));
 * ```
 */
function getPoliciesForTarget(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:organizations/getPoliciesForTarget:getPoliciesForTarget", {
        "filter": args.filter,
        "targetId": args.targetId,
    }, opts);
}
exports.getPoliciesForTarget = getPoliciesForTarget;
/**
 * Data source for managing an AWS Organizations Policies For Target.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const example = aws.organizations.getOrganization({});
 * const exampleGetPoliciesForTarget = example.then(example => aws.organizations.getPoliciesForTarget({
 *     targetId: example.roots?.[0]?.id,
 *     filter: "SERVICE_CONTROL_POLICY",
 * }));
 * const exampleGetPolicy = exampleGetPoliciesForTarget.then(exampleGetPoliciesForTarget => std.toset({
 *     input: exampleGetPoliciesForTarget.ids,
 * })).then(invoke => .reduce((__obj, [__key, __value]) => ({ ...__obj, [__key]: aws.organizations.getPolicy({
 *     policyId: __value,
 * }) })));
 * ```
 */
function getPoliciesForTargetOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:organizations/getPoliciesForTarget:getPoliciesForTarget", {
        "filter": args.filter,
        "targetId": args.targetId,
    }, opts);
}
exports.getPoliciesForTargetOutput = getPoliciesForTargetOutput;
//# sourceMappingURL=getPoliciesForTarget.js.map