"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCloudAutonomousVmClustersOutput = exports.getCloudAutonomousVmClusters = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for managing cloud autonomous vm clusters in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudAutonomousVmClusters({});
 * ```
 */
function getCloudAutonomousVmClusters(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getCloudAutonomousVmClusters:getCloudAutonomousVmClusters", {
        "region": args.region,
    }, opts);
}
exports.getCloudAutonomousVmClusters = getCloudAutonomousVmClusters;
/**
 * Data source for managing cloud autonomous vm clusters in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudAutonomousVmClusters({});
 * ```
 */
function getCloudAutonomousVmClustersOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getCloudAutonomousVmClusters:getCloudAutonomousVmClusters", {
        "region": args.region,
    }, opts);
}
exports.getCloudAutonomousVmClustersOutput = getCloudAutonomousVmClustersOutput;
//# sourceMappingURL=getCloudAutonomousVmClusters.js.map