"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.TargetAccountConfiguration = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages an AWS FIS (Fault Injection Simulator) Target Account Configuration.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = new aws.fis.TargetAccountConfiguration("example", {
 *     experimentTemplateId: exampleAwsFisExperimentTemplate.id,
 *     accountId: current.accountId,
 *     roleArn: fisRole.arn,
 *     description: "Example",
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import FIS (Fault Injection Simulator) Target Account Configuration using the `account_id,experiment_template_id`. For example:
 *
 * ```sh
 * $ pulumi import aws:fis/targetAccountConfiguration:TargetAccountConfiguration example 123456789012,abcd123456789
 * ```
 */
class TargetAccountConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing TargetAccountConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new TargetAccountConfiguration(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of TargetAccountConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TargetAccountConfiguration.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["description"] = state?.description;
            resourceInputs["experimentTemplateId"] = state?.experimentTemplateId;
            resourceInputs["region"] = state?.region;
            resourceInputs["roleArn"] = state?.roleArn;
        }
        else {
            const args = argsOrState;
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.experimentTemplateId === undefined && !opts.urn) {
                throw new Error("Missing required property 'experimentTemplateId'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["description"] = args?.description;
            resourceInputs["experimentTemplateId"] = args?.experimentTemplateId;
            resourceInputs["region"] = args?.region;
            resourceInputs["roleArn"] = args?.roleArn;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TargetAccountConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}
exports.TargetAccountConfiguration = TargetAccountConfiguration;
/** @internal */
TargetAccountConfiguration.__pulumiType = 'aws:fis/targetAccountConfiguration:TargetAccountConfiguration';
//# sourceMappingURL=targetAccountConfiguration.js.map