"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProvisionedModelThroughput = exports.InferenceProfile = exports.GuardrailVersion = exports.Guardrail = exports.getInferenceProfilesOutput = exports.getInferenceProfiles = exports.getInferenceProfileOutput = exports.getInferenceProfile = exports.getCustomModelsOutput = exports.getCustomModels = exports.getCustomModelOutput = exports.getCustomModel = exports.getAgentAgentVersionsOutput = exports.getAgentAgentVersions = exports.CustomModel = exports.AgentcoreWorkloadIdentity = exports.AgentcoreTokenVaultCmk = exports.AgentcoreOauth2CredentialProvider = exports.AgentcoreMemoryStrategy = exports.AgentcoreMemory = exports.AgentcoreGatewayTarget = exports.AgentcoreGateway = exports.AgentcoreCodeInterpreter = exports.AgentcoreBrowser = exports.AgentcoreApiKeyCredentialProvider = exports.AgentcoreAgentRuntimeEndpoint = exports.AgentcoreAgentRuntime = exports.AgentPrompt = exports.AgentKnowledgeBase = exports.AgentFlow = exports.AgentDataSource = exports.AgentAgentKnowledgeBaseAssociation = exports.AgentAgentCollaborator = exports.AgentAgentAlias = exports.AgentAgentActionGroup = exports.AgentAgent = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.AgentAgent = null;
utilities.lazyLoad(exports, ["AgentAgent"], () => require("./agentAgent"));
exports.AgentAgentActionGroup = null;
utilities.lazyLoad(exports, ["AgentAgentActionGroup"], () => require("./agentAgentActionGroup"));
exports.AgentAgentAlias = null;
utilities.lazyLoad(exports, ["AgentAgentAlias"], () => require("./agentAgentAlias"));
exports.AgentAgentCollaborator = null;
utilities.lazyLoad(exports, ["AgentAgentCollaborator"], () => require("./agentAgentCollaborator"));
exports.AgentAgentKnowledgeBaseAssociation = null;
utilities.lazyLoad(exports, ["AgentAgentKnowledgeBaseAssociation"], () => require("./agentAgentKnowledgeBaseAssociation"));
exports.AgentDataSource = null;
utilities.lazyLoad(exports, ["AgentDataSource"], () => require("./agentDataSource"));
exports.AgentFlow = null;
utilities.lazyLoad(exports, ["AgentFlow"], () => require("./agentFlow"));
exports.AgentKnowledgeBase = null;
utilities.lazyLoad(exports, ["AgentKnowledgeBase"], () => require("./agentKnowledgeBase"));
exports.AgentPrompt = null;
utilities.lazyLoad(exports, ["AgentPrompt"], () => require("./agentPrompt"));
exports.AgentcoreAgentRuntime = null;
utilities.lazyLoad(exports, ["AgentcoreAgentRuntime"], () => require("./agentcoreAgentRuntime"));
exports.AgentcoreAgentRuntimeEndpoint = null;
utilities.lazyLoad(exports, ["AgentcoreAgentRuntimeEndpoint"], () => require("./agentcoreAgentRuntimeEndpoint"));
exports.AgentcoreApiKeyCredentialProvider = null;
utilities.lazyLoad(exports, ["AgentcoreApiKeyCredentialProvider"], () => require("./agentcoreApiKeyCredentialProvider"));
exports.AgentcoreBrowser = null;
utilities.lazyLoad(exports, ["AgentcoreBrowser"], () => require("./agentcoreBrowser"));
exports.AgentcoreCodeInterpreter = null;
utilities.lazyLoad(exports, ["AgentcoreCodeInterpreter"], () => require("./agentcoreCodeInterpreter"));
exports.AgentcoreGateway = null;
utilities.lazyLoad(exports, ["AgentcoreGateway"], () => require("./agentcoreGateway"));
exports.AgentcoreGatewayTarget = null;
utilities.lazyLoad(exports, ["AgentcoreGatewayTarget"], () => require("./agentcoreGatewayTarget"));
exports.AgentcoreMemory = null;
utilities.lazyLoad(exports, ["AgentcoreMemory"], () => require("./agentcoreMemory"));
exports.AgentcoreMemoryStrategy = null;
utilities.lazyLoad(exports, ["AgentcoreMemoryStrategy"], () => require("./agentcoreMemoryStrategy"));
exports.AgentcoreOauth2CredentialProvider = null;
utilities.lazyLoad(exports, ["AgentcoreOauth2CredentialProvider"], () => require("./agentcoreOauth2CredentialProvider"));
exports.AgentcoreTokenVaultCmk = null;
utilities.lazyLoad(exports, ["AgentcoreTokenVaultCmk"], () => require("./agentcoreTokenVaultCmk"));
exports.AgentcoreWorkloadIdentity = null;
utilities.lazyLoad(exports, ["AgentcoreWorkloadIdentity"], () => require("./agentcoreWorkloadIdentity"));
exports.CustomModel = null;
utilities.lazyLoad(exports, ["CustomModel"], () => require("./customModel"));
exports.getAgentAgentVersions = null;
exports.getAgentAgentVersionsOutput = null;
utilities.lazyLoad(exports, ["getAgentAgentVersions", "getAgentAgentVersionsOutput"], () => require("./getAgentAgentVersions"));
exports.getCustomModel = null;
exports.getCustomModelOutput = null;
utilities.lazyLoad(exports, ["getCustomModel", "getCustomModelOutput"], () => require("./getCustomModel"));
exports.getCustomModels = null;
exports.getCustomModelsOutput = null;
utilities.lazyLoad(exports, ["getCustomModels", "getCustomModelsOutput"], () => require("./getCustomModels"));
exports.getInferenceProfile = null;
exports.getInferenceProfileOutput = null;
utilities.lazyLoad(exports, ["getInferenceProfile", "getInferenceProfileOutput"], () => require("./getInferenceProfile"));
exports.getInferenceProfiles = null;
exports.getInferenceProfilesOutput = null;
utilities.lazyLoad(exports, ["getInferenceProfiles", "getInferenceProfilesOutput"], () => require("./getInferenceProfiles"));
exports.Guardrail = null;
utilities.lazyLoad(exports, ["Guardrail"], () => require("./guardrail"));
exports.GuardrailVersion = null;
utilities.lazyLoad(exports, ["GuardrailVersion"], () => require("./guardrailVersion"));
exports.InferenceProfile = null;
utilities.lazyLoad(exports, ["InferenceProfile"], () => require("./inferenceProfile"));
exports.ProvisionedModelThroughput = null;
utilities.lazyLoad(exports, ["ProvisionedModelThroughput"], () => require("./provisionedModelThroughput"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "aws:bedrock/agentAgent:AgentAgent":
                return new exports.AgentAgent(name, undefined, { urn });
            case "aws:bedrock/agentAgentActionGroup:AgentAgentActionGroup":
                return new exports.AgentAgentActionGroup(name, undefined, { urn });
            case "aws:bedrock/agentAgentAlias:AgentAgentAlias":
                return new exports.AgentAgentAlias(name, undefined, { urn });
            case "aws:bedrock/agentAgentCollaborator:AgentAgentCollaborator":
                return new exports.AgentAgentCollaborator(name, undefined, { urn });
            case "aws:bedrock/agentAgentKnowledgeBaseAssociation:AgentAgentKnowledgeBaseAssociation":
                return new exports.AgentAgentKnowledgeBaseAssociation(name, undefined, { urn });
            case "aws:bedrock/agentDataSource:AgentDataSource":
                return new exports.AgentDataSource(name, undefined, { urn });
            case "aws:bedrock/agentFlow:AgentFlow":
                return new exports.AgentFlow(name, undefined, { urn });
            case "aws:bedrock/agentKnowledgeBase:AgentKnowledgeBase":
                return new exports.AgentKnowledgeBase(name, undefined, { urn });
            case "aws:bedrock/agentPrompt:AgentPrompt":
                return new exports.AgentPrompt(name, undefined, { urn });
            case "aws:bedrock/agentcoreAgentRuntime:AgentcoreAgentRuntime":
                return new exports.AgentcoreAgentRuntime(name, undefined, { urn });
            case "aws:bedrock/agentcoreAgentRuntimeEndpoint:AgentcoreAgentRuntimeEndpoint":
                return new exports.AgentcoreAgentRuntimeEndpoint(name, undefined, { urn });
            case "aws:bedrock/agentcoreApiKeyCredentialProvider:AgentcoreApiKeyCredentialProvider":
                return new exports.AgentcoreApiKeyCredentialProvider(name, undefined, { urn });
            case "aws:bedrock/agentcoreBrowser:AgentcoreBrowser":
                return new exports.AgentcoreBrowser(name, undefined, { urn });
            case "aws:bedrock/agentcoreCodeInterpreter:AgentcoreCodeInterpreter":
                return new exports.AgentcoreCodeInterpreter(name, undefined, { urn });
            case "aws:bedrock/agentcoreGateway:AgentcoreGateway":
                return new exports.AgentcoreGateway(name, undefined, { urn });
            case "aws:bedrock/agentcoreGatewayTarget:AgentcoreGatewayTarget":
                return new exports.AgentcoreGatewayTarget(name, undefined, { urn });
            case "aws:bedrock/agentcoreMemory:AgentcoreMemory":
                return new exports.AgentcoreMemory(name, undefined, { urn });
            case "aws:bedrock/agentcoreMemoryStrategy:AgentcoreMemoryStrategy":
                return new exports.AgentcoreMemoryStrategy(name, undefined, { urn });
            case "aws:bedrock/agentcoreOauth2CredentialProvider:AgentcoreOauth2CredentialProvider":
                return new exports.AgentcoreOauth2CredentialProvider(name, undefined, { urn });
            case "aws:bedrock/agentcoreTokenVaultCmk:AgentcoreTokenVaultCmk":
                return new exports.AgentcoreTokenVaultCmk(name, undefined, { urn });
            case "aws:bedrock/agentcoreWorkloadIdentity:AgentcoreWorkloadIdentity":
                return new exports.AgentcoreWorkloadIdentity(name, undefined, { urn });
            case "aws:bedrock/customModel:CustomModel":
                return new exports.CustomModel(name, undefined, { urn });
            case "aws:bedrock/guardrail:Guardrail":
                return new exports.Guardrail(name, undefined, { urn });
            case "aws:bedrock/guardrailVersion:GuardrailVersion":
                return new exports.GuardrailVersion(name, undefined, { urn });
            case "aws:bedrock/inferenceProfile:InferenceProfile":
                return new exports.InferenceProfile(name, undefined, { urn });
            case "aws:bedrock/provisionedModelThroughput:ProvisionedModelThroughput":
                return new exports.ProvisionedModelThroughput(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aws", "bedrock/agentAgent", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentAgentActionGroup", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentAgentAlias", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentAgentCollaborator", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentAgentKnowledgeBaseAssociation", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentDataSource", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentFlow", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentKnowledgeBase", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentPrompt", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreAgentRuntime", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreAgentRuntimeEndpoint", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreApiKeyCredentialProvider", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreBrowser", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreCodeInterpreter", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreGateway", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreGatewayTarget", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreMemory", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreMemoryStrategy", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreOauth2CredentialProvider", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreTokenVaultCmk", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/agentcoreWorkloadIdentity", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/customModel", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/guardrail", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/guardrailVersion", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/inferenceProfile", _module);
pulumi.runtime.registerResourceModule("aws", "bedrock/provisionedModelThroughput", _module);
//# sourceMappingURL=index.js.map