"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getNetworksOutput = exports.getNetworks = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for to retrieve networks from AWS for Oracle Database@AWS.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetworks({});
 * ```
 */
function getNetworks(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getNetworks:getNetworks", {
        "region": args.region,
    }, opts);
}
exports.getNetworks = getNetworks;
/**
 * Data source for to retrieve networks from AWS for Oracle Database@AWS.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetworks({});
 * ```
 */
function getNetworksOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getNetworks:getNetworks", {
        "region": args.region,
    }, opts);
}
exports.getNetworksOutput = getNetworksOutput;
//# sourceMappingURL=getNetworks.js.map