"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getGlobalClusterOutput = exports.getGlobalCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for managing an AWS RDS (Relational Database) Global Cluster.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.rds.getGlobalCluster({
 *     identifier: test.globalClusterIdentifier,
 * });
 * ```
 */
function getGlobalCluster(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:rds/getGlobalCluster:getGlobalCluster", {
        "identifier": args.identifier,
        "region": args.region,
    }, opts);
}
exports.getGlobalCluster = getGlobalCluster;
/**
 * Data source for managing an AWS RDS (Relational Database) Global Cluster.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.rds.getGlobalCluster({
 *     identifier: test.globalClusterIdentifier,
 * });
 * ```
 */
function getGlobalClusterOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:rds/getGlobalCluster:getGlobalCluster", {
        "identifier": args.identifier,
        "region": args.region,
    }, opts);
}
exports.getGlobalClusterOutput = getGlobalClusterOutput;
//# sourceMappingURL=getGlobalCluster.js.map