"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDbNodeOutput = exports.getDbNode = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for manging db nodes linked to cloud vm cluster of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbNode({
 *     cloudVmClusterId: "cloud_vm_cluster_id",
 *     id: "db_node_id",
 * });
 * ```
 */
function getDbNode(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getDbNode:getDbNode", {
        "cloudVmClusterId": args.cloudVmClusterId,
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getDbNode = getDbNode;
/**
 * Data source for manging db nodes linked to cloud vm cluster of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbNode({
 *     cloudVmClusterId: "cloud_vm_cluster_id",
 *     id: "db_node_id",
 * });
 * ```
 */
function getDbNodeOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getDbNode:getDbNode", {
        "cloudVmClusterId": args.cloudVmClusterId,
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getDbNodeOutput = getDbNodeOutput;
//# sourceMappingURL=getDbNode.js.map