"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.NetworkPeeringConnection = exports.Network = exports.getNetworksOutput = exports.getNetworks = exports.getNetworkPeeringConnectionsOutput = exports.getNetworkPeeringConnections = exports.getNetworkPeeringConnectionOutput = exports.getNetworkPeeringConnection = exports.getNetworkOutput = exports.getNetwork = exports.getGiVersionsOutput = exports.getGiVersions = exports.getDbSystemShapesOutput = exports.getDbSystemShapes = exports.getDbServersOutput = exports.getDbServers = exports.getDbServerOutput = exports.getDbServer = exports.getDbNodesOutput = exports.getDbNodes = exports.getDbNodeOutput = exports.getDbNode = exports.getCloudVmClustersOutput = exports.getCloudVmClusters = exports.getCloudVmClusterOutput = exports.getCloudVmCluster = exports.getCloudExadataInfrastructuresOutput = exports.getCloudExadataInfrastructures = exports.getCloudExadataInfrastructureOutput = exports.getCloudExadataInfrastructure = exports.getCloudAutonomousVmClustersOutput = exports.getCloudAutonomousVmClusters = exports.getCloudAutonomousVmClusterOutput = exports.getCloudAutonomousVmCluster = exports.CloudVmCluster = exports.CloudExadataInfrastructure = exports.CloudAutonomousVmCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.CloudAutonomousVmCluster = null;
utilities.lazyLoad(exports, ["CloudAutonomousVmCluster"], () => require("./cloudAutonomousVmCluster"));
exports.CloudExadataInfrastructure = null;
utilities.lazyLoad(exports, ["CloudExadataInfrastructure"], () => require("./cloudExadataInfrastructure"));
exports.CloudVmCluster = null;
utilities.lazyLoad(exports, ["CloudVmCluster"], () => require("./cloudVmCluster"));
exports.getCloudAutonomousVmCluster = null;
exports.getCloudAutonomousVmClusterOutput = null;
utilities.lazyLoad(exports, ["getCloudAutonomousVmCluster", "getCloudAutonomousVmClusterOutput"], () => require("./getCloudAutonomousVmCluster"));
exports.getCloudAutonomousVmClusters = null;
exports.getCloudAutonomousVmClustersOutput = null;
utilities.lazyLoad(exports, ["getCloudAutonomousVmClusters", "getCloudAutonomousVmClustersOutput"], () => require("./getCloudAutonomousVmClusters"));
exports.getCloudExadataInfrastructure = null;
exports.getCloudExadataInfrastructureOutput = null;
utilities.lazyLoad(exports, ["getCloudExadataInfrastructure", "getCloudExadataInfrastructureOutput"], () => require("./getCloudExadataInfrastructure"));
exports.getCloudExadataInfrastructures = null;
exports.getCloudExadataInfrastructuresOutput = null;
utilities.lazyLoad(exports, ["getCloudExadataInfrastructures", "getCloudExadataInfrastructuresOutput"], () => require("./getCloudExadataInfrastructures"));
exports.getCloudVmCluster = null;
exports.getCloudVmClusterOutput = null;
utilities.lazyLoad(exports, ["getCloudVmCluster", "getCloudVmClusterOutput"], () => require("./getCloudVmCluster"));
exports.getCloudVmClusters = null;
exports.getCloudVmClustersOutput = null;
utilities.lazyLoad(exports, ["getCloudVmClusters", "getCloudVmClustersOutput"], () => require("./getCloudVmClusters"));
exports.getDbNode = null;
exports.getDbNodeOutput = null;
utilities.lazyLoad(exports, ["getDbNode", "getDbNodeOutput"], () => require("./getDbNode"));
exports.getDbNodes = null;
exports.getDbNodesOutput = null;
utilities.lazyLoad(exports, ["getDbNodes", "getDbNodesOutput"], () => require("./getDbNodes"));
exports.getDbServer = null;
exports.getDbServerOutput = null;
utilities.lazyLoad(exports, ["getDbServer", "getDbServerOutput"], () => require("./getDbServer"));
exports.getDbServers = null;
exports.getDbServersOutput = null;
utilities.lazyLoad(exports, ["getDbServers", "getDbServersOutput"], () => require("./getDbServers"));
exports.getDbSystemShapes = null;
exports.getDbSystemShapesOutput = null;
utilities.lazyLoad(exports, ["getDbSystemShapes", "getDbSystemShapesOutput"], () => require("./getDbSystemShapes"));
exports.getGiVersions = null;
exports.getGiVersionsOutput = null;
utilities.lazyLoad(exports, ["getGiVersions", "getGiVersionsOutput"], () => require("./getGiVersions"));
exports.getNetwork = null;
exports.getNetworkOutput = null;
utilities.lazyLoad(exports, ["getNetwork", "getNetworkOutput"], () => require("./getNetwork"));
exports.getNetworkPeeringConnection = null;
exports.getNetworkPeeringConnectionOutput = null;
utilities.lazyLoad(exports, ["getNetworkPeeringConnection", "getNetworkPeeringConnectionOutput"], () => require("./getNetworkPeeringConnection"));
exports.getNetworkPeeringConnections = null;
exports.getNetworkPeeringConnectionsOutput = null;
utilities.lazyLoad(exports, ["getNetworkPeeringConnections", "getNetworkPeeringConnectionsOutput"], () => require("./getNetworkPeeringConnections"));
exports.getNetworks = null;
exports.getNetworksOutput = null;
utilities.lazyLoad(exports, ["getNetworks", "getNetworksOutput"], () => require("./getNetworks"));
exports.Network = null;
utilities.lazyLoad(exports, ["Network"], () => require("./network"));
exports.NetworkPeeringConnection = null;
utilities.lazyLoad(exports, ["NetworkPeeringConnection"], () => require("./networkPeeringConnection"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "aws:odb/cloudAutonomousVmCluster:CloudAutonomousVmCluster":
                return new exports.CloudAutonomousVmCluster(name, undefined, { urn });
            case "aws:odb/cloudExadataInfrastructure:CloudExadataInfrastructure":
                return new exports.CloudExadataInfrastructure(name, undefined, { urn });
            case "aws:odb/cloudVmCluster:CloudVmCluster":
                return new exports.CloudVmCluster(name, undefined, { urn });
            case "aws:odb/network:Network":
                return new exports.Network(name, undefined, { urn });
            case "aws:odb/networkPeeringConnection:NetworkPeeringConnection":
                return new exports.NetworkPeeringConnection(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aws", "odb/cloudAutonomousVmCluster", _module);
pulumi.runtime.registerResourceModule("aws", "odb/cloudExadataInfrastructure", _module);
pulumi.runtime.registerResourceModule("aws", "odb/cloudVmCluster", _module);
pulumi.runtime.registerResourceModule("aws", "odb/network", _module);
pulumi.runtime.registerResourceModule("aws", "odb/networkPeeringConnection", _module);
//# sourceMappingURL=index.js.map