"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getPoliciesOutput = exports.getPolicies = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for managing an AWS Organizations Policies.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const example = aws.organizations.getPolicies({
 *     filter: "SERVICE_CONTROL_POLICY",
 * });
 * const exampleGetPolicy = example.then(example => std.toset({
 *     input: example.ids,
 * })).then(invoke => .reduce((__obj, [__key, __value]) => ({ ...__obj, [__key]: aws.organizations.getPolicy({
 *     policyId: __value,
 * }) })));
 * ```
 */
function getPolicies(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:organizations/getPolicies:getPolicies", {
        "filter": args.filter,
    }, opts);
}
exports.getPolicies = getPolicies;
/**
 * Data source for managing an AWS Organizations Policies.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const example = aws.organizations.getPolicies({
 *     filter: "SERVICE_CONTROL_POLICY",
 * });
 * const exampleGetPolicy = example.then(example => std.toset({
 *     input: example.ids,
 * })).then(invoke => .reduce((__obj, [__key, __value]) => ({ ...__obj, [__key]: aws.organizations.getPolicy({
 *     policyId: __value,
 * }) })));
 * ```
 */
function getPoliciesOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:organizations/getPolicies:getPolicies", {
        "filter": args.filter,
    }, opts);
}
exports.getPoliciesOutput = getPoliciesOutput;
//# sourceMappingURL=getPolicies.js.map