"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDbServersOutput = exports.getDbServers = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for manging db servers linked to exadata infrastructure of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbServers({
 *     cloudExadataInfrastructureId: "exadata_infra_id",
 * });
 * ```
 */
function getDbServers(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getDbServers:getDbServers", {
        "cloudExadataInfrastructureId": args.cloudExadataInfrastructureId,
        "region": args.region,
    }, opts);
}
exports.getDbServers = getDbServers;
/**
 * Data source for manging db servers linked to exadata infrastructure of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbServers({
 *     cloudExadataInfrastructureId: "exadata_infra_id",
 * });
 * ```
 */
function getDbServersOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getDbServers:getDbServers", {
        "cloudExadataInfrastructureId": args.cloudExadataInfrastructureId,
        "region": args.region,
    }, opts);
}
exports.getDbServersOutput = getDbServersOutput;
//# sourceMappingURL=getDbServers.js.map