"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDbServerOutput = exports.getDbServer = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for manging db server linked to exadata infrastructure of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbServer({
 *     cloudExadataInfrastructureId: "exadata_infra_id",
 *     id: "db_server_id",
 * });
 * ```
 */
function getDbServer(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getDbServer:getDbServer", {
        "cloudExadataInfrastructureId": args.cloudExadataInfrastructureId,
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getDbServer = getDbServer;
/**
 * Data source for manging db server linked to exadata infrastructure of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbServer({
 *     cloudExadataInfrastructureId: "exadata_infra_id",
 *     id: "db_server_id",
 * });
 * ```
 */
function getDbServerOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getDbServer:getDbServer", {
        "cloudExadataInfrastructureId": args.cloudExadataInfrastructureId,
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getDbServerOutput = getDbServerOutput;
//# sourceMappingURL=getDbServer.js.map