"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudAutonomousVmCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Resource managing cloud autonomous vm cluster in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const avmcWithMinimumParameters = new aws.odb.CloudAutonomousVmCluster("avmc_with_minimum_parameters", {
 *     cloudExadataInfrastructureId: "<aws_odb_cloud_exadata_infrastructure_id>",
 *     odbNetworkId: "<aws_odb_network_id>",
 *     displayName: "my_autonomous_vm_cluster",
 *     autonomousDataStorageSizeInTbs: 5,
 *     memoryPerOracleComputeUnitInGbs: 2,
 *     totalContainerDatabases: 1,
 *     cpuCoreCountPerNode: 40,
 *     licenseModel: "LICENSE_INCLUDED",
 *     dbServers: ["<my_db_server_id>"],
 *     scanListenerPortTls: 8561,
 *     scanListenerPortNonTls: 1024,
 *     maintenanceWindow: {
 *         preference: "NO_PREFERENCE",
 *     },
 * });
 * const avmcWithAllParams = new aws.odb.CloudAutonomousVmCluster("avmc_with_all_params", {
 *     description: "my first avmc",
 *     timeZone: "UTC",
 *     cloudExadataInfrastructureId: "<aws_odb_cloud_exadata_infrastructure_id>",
 *     odbNetworkId: "<aws_odb_network_id>",
 *     displayName: "my_autonomous_vm_cluster",
 *     autonomousDataStorageSizeInTbs: 5,
 *     memoryPerOracleComputeUnitInGbs: 2,
 *     totalContainerDatabases: 1,
 *     cpuCoreCountPerNode: 40,
 *     licenseModel: "LICENSE_INCLUDED",
 *     dbServers: [
 *         "<my_db_server_1>",
 *         "<my_db_server_2>",
 *     ],
 *     scanListenerPortTls: 8561,
 *     scanListenerPortNonTls: 1024,
 *     maintenanceWindow: {
 *         daysOfWeeks: [
 *             {
 *                 name: "MONDAY",
 *             },
 *             {
 *                 name: "TUESDAY",
 *             },
 *         ],
 *         hoursOfDays: [
 *             4,
 *             16,
 *         ],
 *         leadTimeInWeeks: 3,
 *         months: [
 *             {
 *                 name: "FEBRUARY",
 *             },
 *             {
 *                 name: "MAY",
 *             },
 *             {
 *                 name: "AUGUST",
 *             },
 *             {
 *                 name: "NOVEMBER",
 *             },
 *         ],
 *         preference: "CUSTOM_PREFERENCE",
 *         weeksOfMonths: [
 *             2,
 *             4,
 *         ],
 *     },
 *     tags: {
 *         env: "dev",
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import cloud autonomous vm cluster `id`. For example:
 *
 * ```sh
 * $ pulumi import aws:odb/cloudAutonomousVmCluster:CloudAutonomousVmCluster example example
 * ```
 */
class CloudAutonomousVmCluster extends pulumi.CustomResource {
    /**
     * Get an existing CloudAutonomousVmCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new CloudAutonomousVmCluster(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of CloudAutonomousVmCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudAutonomousVmCluster.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["arn"] = state?.arn;
            resourceInputs["autonomousDataStoragePercentage"] = state?.autonomousDataStoragePercentage;
            resourceInputs["autonomousDataStorageSizeInTbs"] = state?.autonomousDataStorageSizeInTbs;
            resourceInputs["availableAutonomousDataStorageSizeInTbs"] = state?.availableAutonomousDataStorageSizeInTbs;
            resourceInputs["availableContainerDatabases"] = state?.availableContainerDatabases;
            resourceInputs["availableCpus"] = state?.availableCpus;
            resourceInputs["cloudExadataInfrastructureId"] = state?.cloudExadataInfrastructureId;
            resourceInputs["computeModel"] = state?.computeModel;
            resourceInputs["cpuCoreCount"] = state?.cpuCoreCount;
            resourceInputs["cpuCoreCountPerNode"] = state?.cpuCoreCountPerNode;
            resourceInputs["cpuPercentage"] = state?.cpuPercentage;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["dataStorageSizeInGbs"] = state?.dataStorageSizeInGbs;
            resourceInputs["dataStorageSizeInTbs"] = state?.dataStorageSizeInTbs;
            resourceInputs["dbServers"] = state?.dbServers;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["exadataStorageInTbsLowestScaledValue"] = state?.exadataStorageInTbsLowestScaledValue;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["isMtlsEnabledVmCluster"] = state?.isMtlsEnabledVmCluster;
            resourceInputs["licenseModel"] = state?.licenseModel;
            resourceInputs["maintenanceWindow"] = state?.maintenanceWindow;
            resourceInputs["maxAcdsLowestScaledValue"] = state?.maxAcdsLowestScaledValue;
            resourceInputs["memoryPerOracleComputeUnitInGbs"] = state?.memoryPerOracleComputeUnitInGbs;
            resourceInputs["memorySizeInGbs"] = state?.memorySizeInGbs;
            resourceInputs["nodeCount"] = state?.nodeCount;
            resourceInputs["nonProvisionableAutonomousContainerDatabases"] = state?.nonProvisionableAutonomousContainerDatabases;
            resourceInputs["ociResourceAnchorName"] = state?.ociResourceAnchorName;
            resourceInputs["ociUrl"] = state?.ociUrl;
            resourceInputs["ocid"] = state?.ocid;
            resourceInputs["odbNetworkId"] = state?.odbNetworkId;
            resourceInputs["odbNodeStorageSizeInGbs"] = state?.odbNodeStorageSizeInGbs;
            resourceInputs["percentProgress"] = state?.percentProgress;
            resourceInputs["provisionableAutonomousContainerDatabases"] = state?.provisionableAutonomousContainerDatabases;
            resourceInputs["provisionedAutonomousContainerDatabases"] = state?.provisionedAutonomousContainerDatabases;
            resourceInputs["provisionedCpus"] = state?.provisionedCpus;
            resourceInputs["reclaimableCpus"] = state?.reclaimableCpus;
            resourceInputs["region"] = state?.region;
            resourceInputs["reservedCpus"] = state?.reservedCpus;
            resourceInputs["scanListenerPortNonTls"] = state?.scanListenerPortNonTls;
            resourceInputs["scanListenerPortTls"] = state?.scanListenerPortTls;
            resourceInputs["shape"] = state?.shape;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusReason"] = state?.statusReason;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tagsAll"] = state?.tagsAll;
            resourceInputs["timeDatabaseSslCertificateExpires"] = state?.timeDatabaseSslCertificateExpires;
            resourceInputs["timeOrdsCertificateExpires"] = state?.timeOrdsCertificateExpires;
            resourceInputs["timeZone"] = state?.timeZone;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["totalContainerDatabases"] = state?.totalContainerDatabases;
        }
        else {
            const args = argsOrState;
            if (args?.autonomousDataStorageSizeInTbs === undefined && !opts.urn) {
                throw new Error("Missing required property 'autonomousDataStorageSizeInTbs'");
            }
            if (args?.cloudExadataInfrastructureId === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudExadataInfrastructureId'");
            }
            if (args?.cpuCoreCountPerNode === undefined && !opts.urn) {
                throw new Error("Missing required property 'cpuCoreCountPerNode'");
            }
            if (args?.dbServers === undefined && !opts.urn) {
                throw new Error("Missing required property 'dbServers'");
            }
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.memoryPerOracleComputeUnitInGbs === undefined && !opts.urn) {
                throw new Error("Missing required property 'memoryPerOracleComputeUnitInGbs'");
            }
            if (args?.odbNetworkId === undefined && !opts.urn) {
                throw new Error("Missing required property 'odbNetworkId'");
            }
            if (args?.scanListenerPortNonTls === undefined && !opts.urn) {
                throw new Error("Missing required property 'scanListenerPortNonTls'");
            }
            if (args?.scanListenerPortTls === undefined && !opts.urn) {
                throw new Error("Missing required property 'scanListenerPortTls'");
            }
            if (args?.totalContainerDatabases === undefined && !opts.urn) {
                throw new Error("Missing required property 'totalContainerDatabases'");
            }
            resourceInputs["autonomousDataStorageSizeInTbs"] = args?.autonomousDataStorageSizeInTbs;
            resourceInputs["cloudExadataInfrastructureId"] = args?.cloudExadataInfrastructureId;
            resourceInputs["cpuCoreCountPerNode"] = args?.cpuCoreCountPerNode;
            resourceInputs["dbServers"] = args?.dbServers;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["isMtlsEnabledVmCluster"] = args?.isMtlsEnabledVmCluster;
            resourceInputs["licenseModel"] = args?.licenseModel;
            resourceInputs["maintenanceWindow"] = args?.maintenanceWindow;
            resourceInputs["memoryPerOracleComputeUnitInGbs"] = args?.memoryPerOracleComputeUnitInGbs;
            resourceInputs["odbNetworkId"] = args?.odbNetworkId;
            resourceInputs["region"] = args?.region;
            resourceInputs["scanListenerPortNonTls"] = args?.scanListenerPortNonTls;
            resourceInputs["scanListenerPortTls"] = args?.scanListenerPortTls;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeZone"] = args?.timeZone;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["totalContainerDatabases"] = args?.totalContainerDatabases;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["autonomousDataStoragePercentage"] = undefined /*out*/;
            resourceInputs["availableAutonomousDataStorageSizeInTbs"] = undefined /*out*/;
            resourceInputs["availableContainerDatabases"] = undefined /*out*/;
            resourceInputs["availableCpus"] = undefined /*out*/;
            resourceInputs["computeModel"] = undefined /*out*/;
            resourceInputs["cpuCoreCount"] = undefined /*out*/;
            resourceInputs["cpuPercentage"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["dataStorageSizeInGbs"] = undefined /*out*/;
            resourceInputs["dataStorageSizeInTbs"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["exadataStorageInTbsLowestScaledValue"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["maxAcdsLowestScaledValue"] = undefined /*out*/;
            resourceInputs["memorySizeInGbs"] = undefined /*out*/;
            resourceInputs["nodeCount"] = undefined /*out*/;
            resourceInputs["nonProvisionableAutonomousContainerDatabases"] = undefined /*out*/;
            resourceInputs["ociResourceAnchorName"] = undefined /*out*/;
            resourceInputs["ociUrl"] = undefined /*out*/;
            resourceInputs["ocid"] = undefined /*out*/;
            resourceInputs["odbNodeStorageSizeInGbs"] = undefined /*out*/;
            resourceInputs["percentProgress"] = undefined /*out*/;
            resourceInputs["provisionableAutonomousContainerDatabases"] = undefined /*out*/;
            resourceInputs["provisionedAutonomousContainerDatabases"] = undefined /*out*/;
            resourceInputs["provisionedCpus"] = undefined /*out*/;
            resourceInputs["reclaimableCpus"] = undefined /*out*/;
            resourceInputs["reservedCpus"] = undefined /*out*/;
            resourceInputs["shape"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["statusReason"] = undefined /*out*/;
            resourceInputs["tagsAll"] = undefined /*out*/;
            resourceInputs["timeDatabaseSslCertificateExpires"] = undefined /*out*/;
            resourceInputs["timeOrdsCertificateExpires"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudAutonomousVmCluster.__pulumiType, name, resourceInputs, opts);
    }
}
exports.CloudAutonomousVmCluster = CloudAutonomousVmCluster;
/** @internal */
CloudAutonomousVmCluster.__pulumiType = 'aws:odb/cloudAutonomousVmCluster:CloudAutonomousVmCluster';
//# sourceMappingURL=cloudAutonomousVmCluster.js.map