"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.CentralizationRuleForOrganization = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.CentralizationRuleForOrganization = null;
utilities.lazyLoad(exports, ["CentralizationRuleForOrganization"], () => require("./centralizationRuleForOrganization"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "aws:observabilityadmin/centralizationRuleForOrganization:CentralizationRuleForOrganization":
                return new exports.CentralizationRuleForOrganization(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aws", "observabilityadmin/centralizationRuleForOrganization", _module);
//# sourceMappingURL=index.js.map