"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCloudExadataInfrastructuresOutput = exports.getCloudExadataInfrastructures = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for exadata infrastructures in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudExadataInfrastructures({});
 * ```
 */
function getCloudExadataInfrastructures(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getCloudExadataInfrastructures:getCloudExadataInfrastructures", {
        "region": args.region,
    }, opts);
}
exports.getCloudExadataInfrastructures = getCloudExadataInfrastructures;
/**
 * Data source for exadata infrastructures in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudExadataInfrastructures({});
 * ```
 */
function getCloudExadataInfrastructuresOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getCloudExadataInfrastructures:getCloudExadataInfrastructures", {
        "region": args.region,
    }, opts);
}
exports.getCloudExadataInfrastructuresOutput = getCloudExadataInfrastructuresOutput;
//# sourceMappingURL=getCloudExadataInfrastructures.js.map