"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebAppCustomization = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Resource for managing an AWS Transfer Family Web App Customization.
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Using `pulumi import`, import Transfer Family Web App Customization using the `web_app_id`. For example:
 *
 * ```sh
 * $ pulumi import aws:transfer/webAppCustomization:WebAppCustomization example webapp-12345678901234567890
 * ```
 */
class WebAppCustomization extends pulumi.CustomResource {
    /**
     * Get an existing WebAppCustomization resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new WebAppCustomization(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of WebAppCustomization.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WebAppCustomization.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["faviconFile"] = state?.faviconFile;
            resourceInputs["logoFile"] = state?.logoFile;
            resourceInputs["region"] = state?.region;
            resourceInputs["title"] = state?.title;
            resourceInputs["webAppId"] = state?.webAppId;
        }
        else {
            const args = argsOrState;
            if (args?.webAppId === undefined && !opts.urn) {
                throw new Error("Missing required property 'webAppId'");
            }
            resourceInputs["faviconFile"] = args?.faviconFile;
            resourceInputs["logoFile"] = args?.logoFile;
            resourceInputs["region"] = args?.region;
            resourceInputs["title"] = args?.title;
            resourceInputs["webAppId"] = args?.webAppId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WebAppCustomization.__pulumiType, name, resourceInputs, opts);
    }
}
exports.WebAppCustomization = WebAppCustomization;
/** @internal */
WebAppCustomization.__pulumiType = 'aws:transfer/webAppCustomization:WebAppCustomization';
//# sourceMappingURL=webAppCustomization.js.map