"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCloudExadataInfrastructureOutput = exports.getCloudExadataInfrastructure = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for exadata infrastructure resource in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudExadataInfrastructure({
 *     id: "example",
 * });
 * ```
 */
function getCloudExadataInfrastructure(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getCloudExadataInfrastructure:getCloudExadataInfrastructure", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getCloudExadataInfrastructure = getCloudExadataInfrastructure;
/**
 * Data source for exadata infrastructure resource in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudExadataInfrastructure({
 *     id: "example",
 * });
 * ```
 */
function getCloudExadataInfrastructureOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getCloudExadataInfrastructure:getCloudExadataInfrastructure", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getCloudExadataInfrastructureOutput = getCloudExadataInfrastructureOutput;
//# sourceMappingURL=getCloudExadataInfrastructure.js.map