"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCloudVmClusterOutput = exports.getCloudVmCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for cloud vm cluster in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudVmCluster({
 *     id: "example-id",
 * });
 * ```
 */
function getCloudVmCluster(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getCloudVmCluster:getCloudVmCluster", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getCloudVmCluster = getCloudVmCluster;
/**
 * Data source for cloud vm cluster in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudVmCluster({
 *     id: "example-id",
 * });
 * ```
 */
function getCloudVmClusterOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getCloudVmCluster:getCloudVmCluster", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getCloudVmClusterOutput = getCloudVmClusterOutput;
//# sourceMappingURL=getCloudVmCluster.js.map