"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getNetworkPeeringConnectionOutput = exports.getNetworkPeeringConnection = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for managing oracle database network peering resource in AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetworkPeeringConnection({
 *     id: "example",
 * });
 * ```
 */
function getNetworkPeeringConnection(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getNetworkPeeringConnection:getNetworkPeeringConnection", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getNetworkPeeringConnection = getNetworkPeeringConnection;
/**
 * Data source for managing oracle database network peering resource in AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetworkPeeringConnection({
 *     id: "example",
 * });
 * ```
 */
function getNetworkPeeringConnectionOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getNetworkPeeringConnection:getNetworkPeeringConnection", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getNetworkPeeringConnectionOutput = getNetworkPeeringConnectionOutput;
//# sourceMappingURL=getNetworkPeeringConnection.js.map