"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentcoreWorkloadIdentity = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages an AWS Bedrock AgentCore Workload Identity. Workload Identity provides OAuth2-based authentication and authorization for AI agents to access external resources securely.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = new aws.bedrock.AgentcoreWorkloadIdentity("example", {
 *     name: "example-workload-identity",
 *     allowedResourceOauth2ReturnUrls: ["https://example.com/callback"],
 * });
 * ```
 *
 * ### Workload Identity with Multiple Return URLs
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = new aws.bedrock.AgentcoreWorkloadIdentity("example", {
 *     name: "example-workload-identity",
 *     allowedResourceOauth2ReturnUrls: [
 *         "https://app.example.com/oauth/callback",
 *         "https://api.example.com/auth/return",
 *         "https://example.com/callback",
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import Bedrock AgentCore Workload Identity using the workload identity name. For example:
 *
 * ```sh
 * $ pulumi import aws:bedrock/agentcoreWorkloadIdentity:AgentcoreWorkloadIdentity example example-workload-identity
 * ```
 */
class AgentcoreWorkloadIdentity extends pulumi.CustomResource {
    /**
     * Get an existing AgentcoreWorkloadIdentity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new AgentcoreWorkloadIdentity(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of AgentcoreWorkloadIdentity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentcoreWorkloadIdentity.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["allowedResourceOauth2ReturnUrls"] = state?.allowedResourceOauth2ReturnUrls;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
            resourceInputs["workloadIdentityArn"] = state?.workloadIdentityArn;
        }
        else {
            const args = argsOrState;
            resourceInputs["allowedResourceOauth2ReturnUrls"] = args?.allowedResourceOauth2ReturnUrls;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["workloadIdentityArn"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentcoreWorkloadIdentity.__pulumiType, name, resourceInputs, opts);
    }
}
exports.AgentcoreWorkloadIdentity = AgentcoreWorkloadIdentity;
/** @internal */
AgentcoreWorkloadIdentity.__pulumiType = 'aws:bedrock/agentcoreWorkloadIdentity:AgentcoreWorkloadIdentity';
//# sourceMappingURL=agentcoreWorkloadIdentity.js.map