"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.InvoiceUnit = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.InvoiceUnit = null;
utilities.lazyLoad(exports, ["InvoiceUnit"], () => require("./invoiceUnit"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "aws:invoicing/invoiceUnit:InvoiceUnit":
                return new exports.InvoiceUnit(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aws", "invoicing/invoiceUnit", _module);
//# sourceMappingURL=index.js.map