"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentcoreTokenVaultCmk = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages the AWS KMS customer master key (CMK) for a token vault.
 *
 * > Deletion of this resource will not modify the CMK, only remove the resource from state.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = new aws.bedrock.AgentcoreTokenVaultCmk("example", {kmsConfiguration: {
 *     keyType: "CustomerManagedKey",
 *     kmsKeyArn: exampleAwsKmsKey.arn,
 * }});
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import token vault CMKs using the token vault ID. For example:
 *
 * ```sh
 * $ pulumi import aws:bedrock/agentcoreTokenVaultCmk:AgentcoreTokenVaultCmk example "default"
 * ```
 */
class AgentcoreTokenVaultCmk extends pulumi.CustomResource {
    /**
     * Get an existing AgentcoreTokenVaultCmk resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new AgentcoreTokenVaultCmk(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of AgentcoreTokenVaultCmk.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentcoreTokenVaultCmk.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["kmsConfiguration"] = state?.kmsConfiguration;
            resourceInputs["region"] = state?.region;
            resourceInputs["tokenVaultId"] = state?.tokenVaultId;
        }
        else {
            const args = argsOrState;
            resourceInputs["kmsConfiguration"] = args?.kmsConfiguration;
            resourceInputs["region"] = args?.region;
            resourceInputs["tokenVaultId"] = args?.tokenVaultId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentcoreTokenVaultCmk.__pulumiType, name, resourceInputs, opts);
    }
}
exports.AgentcoreTokenVaultCmk = AgentcoreTokenVaultCmk;
/** @internal */
AgentcoreTokenVaultCmk.__pulumiType = 'aws:bedrock/agentcoreTokenVaultCmk:AgentcoreTokenVaultCmk';
//# sourceMappingURL=agentcoreTokenVaultCmk.js.map