"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.Scope = exports.Monitor = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.Monitor = null;
utilities.lazyLoad(exports, ["Monitor"], () => require("./monitor"));
exports.Scope = null;
utilities.lazyLoad(exports, ["Scope"], () => require("./scope"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "aws:networkflowmonitor/monitor:Monitor":
                return new exports.Monitor(name, undefined, { urn });
            case "aws:networkflowmonitor/scope:Scope":
                return new exports.Scope(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aws", "networkflowmonitor/monitor", _module);
pulumi.runtime.registerResourceModule("aws", "networkflowmonitor/scope", _module);
//# sourceMappingURL=index.js.map