"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentcoreAgentRuntimeEndpoint = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages an AWS Bedrock AgentCore Agent Runtime Endpoint. Agent Runtime Endpoints provide a network-accessible interface for interacting with agent runtimes, enabling external systems to communicate with and invoke agent capabilities.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = new aws.bedrock.AgentcoreAgentRuntimeEndpoint("example", {
 *     name: "example-endpoint",
 *     agentRuntimeId: exampleAwsBedrockagentcoreAgentRuntime.agentRuntimeId,
 *     description: "Endpoint for agent runtime communication",
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import Bedrock AgentCore Agent Runtime Endpoint using the `agent_runtime_id` and `name` separated by a comma. For example:
 *
 * ```sh
 * $ pulumi import aws:bedrock/agentcoreAgentRuntimeEndpoint:AgentcoreAgentRuntimeEndpoint example AGENTRUNTIME1234567890,example-endpoint
 * ```
 */
class AgentcoreAgentRuntimeEndpoint extends pulumi.CustomResource {
    /**
     * Get an existing AgentcoreAgentRuntimeEndpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new AgentcoreAgentRuntimeEndpoint(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of AgentcoreAgentRuntimeEndpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentcoreAgentRuntimeEndpoint.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["agentRuntimeArn"] = state?.agentRuntimeArn;
            resourceInputs["agentRuntimeEndpointArn"] = state?.agentRuntimeEndpointArn;
            resourceInputs["agentRuntimeId"] = state?.agentRuntimeId;
            resourceInputs["agentRuntimeVersion"] = state?.agentRuntimeVersion;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tagsAll"] = state?.tagsAll;
            resourceInputs["timeouts"] = state?.timeouts;
        }
        else {
            const args = argsOrState;
            if (args?.agentRuntimeId === undefined && !opts.urn) {
                throw new Error("Missing required property 'agentRuntimeId'");
            }
            resourceInputs["agentRuntimeId"] = args?.agentRuntimeId;
            resourceInputs["agentRuntimeVersion"] = args?.agentRuntimeVersion;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["agentRuntimeArn"] = undefined /*out*/;
            resourceInputs["agentRuntimeEndpointArn"] = undefined /*out*/;
            resourceInputs["tagsAll"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentcoreAgentRuntimeEndpoint.__pulumiType, name, resourceInputs, opts);
    }
}
exports.AgentcoreAgentRuntimeEndpoint = AgentcoreAgentRuntimeEndpoint;
/** @internal */
AgentcoreAgentRuntimeEndpoint.__pulumiType = 'aws:bedrock/agentcoreAgentRuntimeEndpoint:AgentcoreAgentRuntimeEndpoint';
//# sourceMappingURL=agentcoreAgentRuntimeEndpoint.js.map