"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getVpnConnectionOutput = exports.getVpnConnection = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Fetches details of a Site-to-Site VPN connection. A Site-to-Site VPN connection is an Internet Protocol security (IPsec) VPN connection between a VPC and an on-premises network.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     filters: [{
 *         name: "customer-gateway-id",
 *         values: ["cgw-1234567890"],
 *     }],
 * });
 * export const vpnConnectionId = example.then(example => example.vpnConnectionId);
 * ```
 *
 * ### Find by VPN Connection ID
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     vpnConnectionId: "vpn-abcd1234567890",
 * });
 * export const gatewayAssociationState = example.then(example => example.gatewayAssociationState);
 * ```
 */
function getVpnConnection(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:ec2/getVpnConnection:getVpnConnection", {
        "filters": args.filters,
        "region": args.region,
        "vpnConnectionId": args.vpnConnectionId,
    }, opts);
}
exports.getVpnConnection = getVpnConnection;
/**
 * Fetches details of a Site-to-Site VPN connection. A Site-to-Site VPN connection is an Internet Protocol security (IPsec) VPN connection between a VPC and an on-premises network.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     filters: [{
 *         name: "customer-gateway-id",
 *         values: ["cgw-1234567890"],
 *     }],
 * });
 * export const vpnConnectionId = example.then(example => example.vpnConnectionId);
 * ```
 *
 * ### Find by VPN Connection ID
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     vpnConnectionId: "vpn-abcd1234567890",
 * });
 * export const gatewayAssociationState = example.then(example => example.gatewayAssociationState);
 * ```
 */
function getVpnConnectionOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:ec2/getVpnConnection:getVpnConnection", {
        "filters": args.filters,
        "region": args.region,
        "vpnConnectionId": args.vpnConnectionId,
    }, opts);
}
exports.getVpnConnectionOutput = getVpnConnectionOutput;
//# sourceMappingURL=getVpnConnection.js.map