"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getNetworkPeeringConnectionsOutput = exports.getNetworkPeeringConnections = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for retrieving all oracle database network peering resource in Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetworkPeeringConnections({});
 * ```
 */
function getNetworkPeeringConnections(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getNetworkPeeringConnections:getNetworkPeeringConnections", {
        "odbPeeringConnections": args.odbPeeringConnections,
        "region": args.region,
    }, opts);
}
exports.getNetworkPeeringConnections = getNetworkPeeringConnections;
/**
 * Data source for retrieving all oracle database network peering resource in Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getNetworkPeeringConnections({});
 * ```
 */
function getNetworkPeeringConnectionsOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getNetworkPeeringConnections:getNetworkPeeringConnections", {
        "odbPeeringConnections": args.odbPeeringConnections,
        "region": args.region,
    }, opts);
}
exports.getNetworkPeeringConnectionsOutput = getNetworkPeeringConnectionsOutput;
//# sourceMappingURL=getNetworkPeeringConnections.js.map