"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getViewsOutput = exports.getViews = void 0;
const utilities = require("../utilities");
exports.getViews = null;
exports.getViewsOutput = null;
utilities.lazyLoad(exports, ["getViews", "getViewsOutput"], () => require("./getViews"));
//# sourceMappingURL=index.js.map