"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.TargetAccountConfiguration = exports.getExperimentTemplatesOutput = exports.getExperimentTemplates = exports.ExperimentTemplate = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.ExperimentTemplate = null;
utilities.lazyLoad(exports, ["ExperimentTemplate"], () => require("./experimentTemplate"));
exports.getExperimentTemplates = null;
exports.getExperimentTemplatesOutput = null;
utilities.lazyLoad(exports, ["getExperimentTemplates", "getExperimentTemplatesOutput"], () => require("./getExperimentTemplates"));
exports.TargetAccountConfiguration = null;
utilities.lazyLoad(exports, ["TargetAccountConfiguration"], () => require("./targetAccountConfiguration"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "aws:fis/experimentTemplate:ExperimentTemplate":
                return new exports.ExperimentTemplate(name, undefined, { urn });
            case "aws:fis/targetAccountConfiguration:TargetAccountConfiguration":
                return new exports.TargetAccountConfiguration(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aws", "fis/experimentTemplate", _module);
pulumi.runtime.registerResourceModule("aws", "fis/targetAccountConfiguration", _module);
//# sourceMappingURL=index.js.map