"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCloudAutonomousVmClusterOutput = exports.getCloudAutonomousVmCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for managing cloud autonomous vm cluster resource in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudAutonomousVmCluster({
 *     id: "example",
 * });
 * ```
 */
function getCloudAutonomousVmCluster(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getCloudAutonomousVmCluster:getCloudAutonomousVmCluster", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getCloudAutonomousVmCluster = getCloudAutonomousVmCluster;
/**
 * Data source for managing cloud autonomous vm cluster resource in AWS for Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getCloudAutonomousVmCluster({
 *     id: "example",
 * });
 * ```
 */
function getCloudAutonomousVmClusterOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getCloudAutonomousVmCluster:getCloudAutonomousVmCluster", {
        "id": args.id,
        "region": args.region,
    }, opts);
}
exports.getCloudAutonomousVmClusterOutput = getCloudAutonomousVmClusterOutput;
//# sourceMappingURL=getCloudAutonomousVmCluster.js.map