"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getWebAclOutput = exports.getWebAcl = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Retrieves the summary of a WAFv2 Web ACL.
 */
function getWebAcl(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:wafv2/getWebAcl:getWebAcl", {
        "name": args.name,
        "region": args.region,
        "resourceArn": args.resourceArn,
        "scope": args.scope,
    }, opts);
}
exports.getWebAcl = getWebAcl;
/**
 * Retrieves the summary of a WAFv2 Web ACL.
 */
function getWebAclOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:wafv2/getWebAcl:getWebAcl", {
        "name": args.name,
        "region": args.region,
        "resourceArn": args.resourceArn,
        "scope": args.scope,
    }, opts);
}
exports.getWebAclOutput = getWebAclOutput;
//# sourceMappingURL=getWebAcl.js.map