"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCoipPoolsOutput = exports.getCoipPools = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Provides information for multiple EC2 Customer-Owned IP Pools, such as their identifiers.
 *
 * ## Example Usage
 *
 * The following shows outputting all COIP Pool Ids.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * export = async () => {
 *     const foo = await aws.ec2.getCoipPools({});
 *     return {
 *         foo: foo.ids,
 *     };
 * }
 * ```
 */
function getCoipPools(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:ec2/getCoipPools:getCoipPools", {
        "filters": args.filters,
        "region": args.region,
        "tags": args.tags,
    }, opts);
}
exports.getCoipPools = getCoipPools;
/**
 * Provides information for multiple EC2 Customer-Owned IP Pools, such as their identifiers.
 *
 * ## Example Usage
 *
 * The following shows outputting all COIP Pool Ids.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * export = async () => {
 *     const foo = await aws.ec2.getCoipPools({});
 *     return {
 *         foo: foo.ids,
 *     };
 * }
 * ```
 */
function getCoipPoolsOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:ec2/getCoipPools:getCoipPools", {
        "filters": args.filters,
        "region": args.region,
        "tags": args.tags,
    }, opts);
}
exports.getCoipPoolsOutput = getCoipPoolsOutput;
//# sourceMappingURL=getCoipPools.js.map