"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDbNodesOutput = exports.getDbNodes = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Data source for manging db nodes linked to cloud vm cluster of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbNodes({
 *     cloudVmClusterId: "example",
 * });
 * ```
 */
function getDbNodes(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:odb/getDbNodes:getDbNodes", {
        "cloudVmClusterId": args.cloudVmClusterId,
        "region": args.region,
    }, opts);
}
exports.getDbNodes = getDbNodes;
/**
 * Data source for manging db nodes linked to cloud vm cluster of Oracle Database@AWS.
 *
 * You can find out more about Oracle Database@AWS from [User Guide](https://docs.aws.amazon.com/odb/latest/UserGuide/what-is-odb.html).
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.odb.getDbNodes({
 *     cloudVmClusterId: "example",
 * });
 * ```
 */
function getDbNodesOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:odb/getDbNodes:getDbNodes", {
        "cloudVmClusterId": args.cloudVmClusterId,
        "region": args.region,
    }, opts);
}
exports.getDbNodesOutput = getDbNodesOutput;
//# sourceMappingURL=getDbNodes.js.map