"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudVmCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const withMinimumParameter = new aws.odb.CloudVmCluster("with_minimum_parameter", {
 *     displayName: "my_vm_cluster",
 *     cloudExadataInfrastructureId: "<aws_odb_cloud_exadata_infrastructure_id>",
 *     cpuCoreCount: 6,
 *     giVersion: "23.0.0.0",
 *     hostnamePrefix: "apollo12",
 *     sshPublicKeys: ["public-ssh-key"],
 *     odbNetworkId: "<aws_odb_network_id>",
 *     isLocalBackupEnabled: true,
 *     isSparseDiskgroupEnabled: true,
 *     licenseModel: "LICENSE_INCLUDED",
 *     dataStorageSizeInTbs: 20,
 *     dbServers: [
 *         "db-server-1",
 *         "db-server-2",
 *     ],
 *     dbNodeStorageSizeInGbs: 120,
 *     memorySizeInGbs: 60,
 *     dataCollectionOptions: {
 *         isDiagnosticsEventsEnabled: false,
 *         isHealthMonitoringEnabled: false,
 *         isIncidentLogsEnabled: false,
 *     },
 * });
 * const withAllParameters = new aws.odb.CloudVmCluster("with_all_parameters", {
 *     displayName: "my_vm_cluster",
 *     cloudExadataInfrastructureId: "<aws_odb_cloud_exadata_infrastructure_id>",
 *     cpuCoreCount: 6,
 *     giVersion: "23.0.0.0",
 *     hostnamePrefix: "apollo12",
 *     sshPublicKeys: ["my-ssh-key"],
 *     odbNetworkId: "<aws_odb_network_id>",
 *     isLocalBackupEnabled: true,
 *     isSparseDiskgroupEnabled: true,
 *     licenseModel: "LICENSE_INCLUDED",
 *     dataStorageSizeInTbs: 20,
 *     dbServers: [
 *         "my-dbserver-1",
 *         "my-db-server-2",
 *     ],
 *     dbNodeStorageSizeInGbs: 120,
 *     memorySizeInGbs: 60,
 *     clusterName: "julia-13",
 *     timezone: "UTC",
 *     scanListenerPortTcp: 1521,
 *     tags: {
 *         env: "dev",
 *     },
 *     dataCollectionOptions: {
 *         isDiagnosticsEventsEnabled: true,
 *         isHealthMonitoringEnabled: true,
 *         isIncidentLogsEnabled: true,
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import cloud vm cluster using the `id`. For example:
 *
 * ```sh
 * $ pulumi import aws:odb/cloudVmCluster:CloudVmCluster example example
 * ```
 */
class CloudVmCluster extends pulumi.CustomResource {
    /**
     * Get an existing CloudVmCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new CloudVmCluster(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of CloudVmCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudVmCluster.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["arn"] = state?.arn;
            resourceInputs["cloudExadataInfrastructureId"] = state?.cloudExadataInfrastructureId;
            resourceInputs["clusterName"] = state?.clusterName;
            resourceInputs["computeModel"] = state?.computeModel;
            resourceInputs["cpuCoreCount"] = state?.cpuCoreCount;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["dataCollectionOptions"] = state?.dataCollectionOptions;
            resourceInputs["dataStorageSizeInTbs"] = state?.dataStorageSizeInTbs;
            resourceInputs["dbNodeStorageSizeInGbs"] = state?.dbNodeStorageSizeInGbs;
            resourceInputs["dbServers"] = state?.dbServers;
            resourceInputs["diskRedundancy"] = state?.diskRedundancy;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["giVersion"] = state?.giVersion;
            resourceInputs["giVersionComputed"] = state?.giVersionComputed;
            resourceInputs["hostnamePrefix"] = state?.hostnamePrefix;
            resourceInputs["hostnamePrefixComputed"] = state?.hostnamePrefixComputed;
            resourceInputs["iormConfigCaches"] = state?.iormConfigCaches;
            resourceInputs["isLocalBackupEnabled"] = state?.isLocalBackupEnabled;
            resourceInputs["isSparseDiskgroupEnabled"] = state?.isSparseDiskgroupEnabled;
            resourceInputs["lastUpdateHistoryEntryId"] = state?.lastUpdateHistoryEntryId;
            resourceInputs["licenseModel"] = state?.licenseModel;
            resourceInputs["listenerPort"] = state?.listenerPort;
            resourceInputs["memorySizeInGbs"] = state?.memorySizeInGbs;
            resourceInputs["nodeCount"] = state?.nodeCount;
            resourceInputs["ociResourceAnchorName"] = state?.ociResourceAnchorName;
            resourceInputs["ociUrl"] = state?.ociUrl;
            resourceInputs["ocid"] = state?.ocid;
            resourceInputs["odbNetworkId"] = state?.odbNetworkId;
            resourceInputs["percentProgress"] = state?.percentProgress;
            resourceInputs["region"] = state?.region;
            resourceInputs["scanDnsName"] = state?.scanDnsName;
            resourceInputs["scanDnsRecordId"] = state?.scanDnsRecordId;
            resourceInputs["scanIpIds"] = state?.scanIpIds;
            resourceInputs["scanListenerPortTcp"] = state?.scanListenerPortTcp;
            resourceInputs["shape"] = state?.shape;
            resourceInputs["sshPublicKeys"] = state?.sshPublicKeys;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusReason"] = state?.statusReason;
            resourceInputs["storageSizeInGbs"] = state?.storageSizeInGbs;
            resourceInputs["systemVersion"] = state?.systemVersion;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tagsAll"] = state?.tagsAll;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["timezone"] = state?.timezone;
            resourceInputs["vipIds"] = state?.vipIds;
        }
        else {
            const args = argsOrState;
            if (args?.cloudExadataInfrastructureId === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudExadataInfrastructureId'");
            }
            if (args?.cpuCoreCount === undefined && !opts.urn) {
                throw new Error("Missing required property 'cpuCoreCount'");
            }
            if (args?.dataStorageSizeInTbs === undefined && !opts.urn) {
                throw new Error("Missing required property 'dataStorageSizeInTbs'");
            }
            if (args?.dbServers === undefined && !opts.urn) {
                throw new Error("Missing required property 'dbServers'");
            }
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.giVersion === undefined && !opts.urn) {
                throw new Error("Missing required property 'giVersion'");
            }
            if (args?.hostnamePrefix === undefined && !opts.urn) {
                throw new Error("Missing required property 'hostnamePrefix'");
            }
            if (args?.odbNetworkId === undefined && !opts.urn) {
                throw new Error("Missing required property 'odbNetworkId'");
            }
            if (args?.sshPublicKeys === undefined && !opts.urn) {
                throw new Error("Missing required property 'sshPublicKeys'");
            }
            resourceInputs["cloudExadataInfrastructureId"] = args?.cloudExadataInfrastructureId;
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["cpuCoreCount"] = args?.cpuCoreCount;
            resourceInputs["dataCollectionOptions"] = args?.dataCollectionOptions;
            resourceInputs["dataStorageSizeInTbs"] = args?.dataStorageSizeInTbs;
            resourceInputs["dbNodeStorageSizeInGbs"] = args?.dbNodeStorageSizeInGbs;
            resourceInputs["dbServers"] = args?.dbServers;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["giVersion"] = args?.giVersion;
            resourceInputs["hostnamePrefix"] = args?.hostnamePrefix;
            resourceInputs["isLocalBackupEnabled"] = args?.isLocalBackupEnabled;
            resourceInputs["isSparseDiskgroupEnabled"] = args?.isSparseDiskgroupEnabled;
            resourceInputs["licenseModel"] = args?.licenseModel;
            resourceInputs["memorySizeInGbs"] = args?.memorySizeInGbs;
            resourceInputs["odbNetworkId"] = args?.odbNetworkId;
            resourceInputs["region"] = args?.region;
            resourceInputs["scanListenerPortTcp"] = args?.scanListenerPortTcp;
            resourceInputs["sshPublicKeys"] = args?.sshPublicKeys;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["timezone"] = args?.timezone;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["computeModel"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["diskRedundancy"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["giVersionComputed"] = undefined /*out*/;
            resourceInputs["hostnamePrefixComputed"] = undefined /*out*/;
            resourceInputs["iormConfigCaches"] = undefined /*out*/;
            resourceInputs["lastUpdateHistoryEntryId"] = undefined /*out*/;
            resourceInputs["listenerPort"] = undefined /*out*/;
            resourceInputs["nodeCount"] = undefined /*out*/;
            resourceInputs["ociResourceAnchorName"] = undefined /*out*/;
            resourceInputs["ociUrl"] = undefined /*out*/;
            resourceInputs["ocid"] = undefined /*out*/;
            resourceInputs["percentProgress"] = undefined /*out*/;
            resourceInputs["scanDnsName"] = undefined /*out*/;
            resourceInputs["scanDnsRecordId"] = undefined /*out*/;
            resourceInputs["scanIpIds"] = undefined /*out*/;
            resourceInputs["shape"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["statusReason"] = undefined /*out*/;
            resourceInputs["storageSizeInGbs"] = undefined /*out*/;
            resourceInputs["systemVersion"] = undefined /*out*/;
            resourceInputs["tagsAll"] = undefined /*out*/;
            resourceInputs["vipIds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudVmCluster.__pulumiType, name, resourceInputs, opts);
    }
}
exports.CloudVmCluster = CloudVmCluster;
/** @internal */
CloudVmCluster.__pulumiType = 'aws:odb/cloudVmCluster:CloudVmCluster';
//# sourceMappingURL=cloudVmCluster.js.map