"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelPackageGroupPolicy = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Provides a SageMaker AI Model Package Group Policy resource.
 *
 * ## Example Usage
 *
 * ### Basic usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as std from "@pulumi/std";
 *
 * const current = aws.getCallerIdentity({});
 * const exampleModelPackageGroup = new aws.sagemaker.ModelPackageGroup("example", {modelPackageGroupName: "example"});
 * const example = pulumi.all([exampleModelPackageGroup.arn, current]).apply(([arn, current]) => aws.iam.getPolicyDocumentOutput({
 *     statements: [{
 *         sid: "AddPermModelPackageGroup",
 *         actions: [
 *             "sagemaker:DescribeModelPackage",
 *             "sagemaker:ListModelPackages",
 *         ],
 *         resources: [arn],
 *         principals: [{
 *             identifiers: [current.accountId],
 *             type: "AWS",
 *         }],
 *     }],
 * }));
 * const exampleModelPackageGroupPolicy = new aws.sagemaker.ModelPackageGroupPolicy("example", {
 *     modelPackageGroupName: exampleModelPackageGroup.modelPackageGroupName,
 *     resourcePolicy: pulumi.jsonStringify(example.apply(example => std.jsondecodeOutput({
 *         input: example.json,
 *     })).apply(invoke => invoke.result)),
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import SageMaker AI Model Package Groups using the `name`. For example:
 *
 * ```sh
 * $ pulumi import aws:sagemaker/modelPackageGroupPolicy:ModelPackageGroupPolicy example example
 * ```
 */
class ModelPackageGroupPolicy extends pulumi.CustomResource {
    /**
     * Get an existing ModelPackageGroupPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new ModelPackageGroupPolicy(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of ModelPackageGroupPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ModelPackageGroupPolicy.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["modelPackageGroupName"] = state?.modelPackageGroupName;
            resourceInputs["region"] = state?.region;
            resourceInputs["resourcePolicy"] = state?.resourcePolicy;
        }
        else {
            const args = argsOrState;
            if (args?.modelPackageGroupName === undefined && !opts.urn) {
                throw new Error("Missing required property 'modelPackageGroupName'");
            }
            if (args?.resourcePolicy === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourcePolicy'");
            }
            resourceInputs["modelPackageGroupName"] = args?.modelPackageGroupName;
            resourceInputs["region"] = args?.region;
            resourceInputs["resourcePolicy"] = args?.resourcePolicy;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ModelPackageGroupPolicy.__pulumiType, name, resourceInputs, opts);
    }
}
exports.ModelPackageGroupPolicy = ModelPackageGroupPolicy;
/** @internal */
ModelPackageGroupPolicy.__pulumiType = 'aws:sagemaker/modelPackageGroupPolicy:ModelPackageGroupPolicy';
//# sourceMappingURL=modelPackageGroupPolicy.js.map