"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdentityCenterConfiguration = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages an AWS Lake Formation Identity Center Configuration.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ssoadmin.getInstances({});
 * const identityCenterInstanceArn = example.then(example => example.arns?.[0]);
 * const exampleIdentityCenterConfiguration = new aws.lakeformation.IdentityCenterConfiguration("example", {instanceArn: identityCenterInstanceArn});
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import Lake Formation Identity Center Configuration using the `catalog_id`. For example:
 *
 * ```sh
 * $ pulumi import aws:lakeformation/identityCenterConfiguration:IdentityCenterConfiguration example 123456789012
 * ```
 */
class IdentityCenterConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing IdentityCenterConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new IdentityCenterConfiguration(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of IdentityCenterConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityCenterConfiguration.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["applicationArn"] = state?.applicationArn;
            resourceInputs["catalogId"] = state?.catalogId;
            resourceInputs["instanceArn"] = state?.instanceArn;
            resourceInputs["region"] = state?.region;
            resourceInputs["resourceShare"] = state?.resourceShare;
        }
        else {
            const args = argsOrState;
            if (args?.instanceArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'instanceArn'");
            }
            resourceInputs["catalogId"] = args?.catalogId;
            resourceInputs["instanceArn"] = args?.instanceArn;
            resourceInputs["region"] = args?.region;
            resourceInputs["applicationArn"] = undefined /*out*/;
            resourceInputs["resourceShare"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IdentityCenterConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}
exports.IdentityCenterConfiguration = IdentityCenterConfiguration;
/** @internal */
IdentityCenterConfiguration.__pulumiType = 'aws:lakeformation/identityCenterConfiguration:IdentityCenterConfiguration';
//# sourceMappingURL=identityCenterConfiguration.js.map