"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getViewsOutput = exports.getViews = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Provides details about an AWS Billing Views.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.billing.getViews({
 *     billingViewTypes: ["PRIMARY"],
 * });
 * export const primaryViewArnByTypes = example.then(example => example.billingViews?.[0]?.arn);
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.billing.getViews({});
 * export const viewArns = example.then(example => .map(view => (view.arn)));
 * export const primaryViewArnByName = example.then(example => .filter(view => view.name == "Primary View").map(view => (view.arn))[0]);
 * ```
 */
function getViews(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:billing/getViews:getViews", {
        "billingViewTypes": args.billingViewTypes,
    }, opts);
}
exports.getViews = getViews;
/**
 * Provides details about an AWS Billing Views.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.billing.getViews({
 *     billingViewTypes: ["PRIMARY"],
 * });
 * export const primaryViewArnByTypes = example.then(example => example.billingViews?.[0]?.arn);
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.billing.getViews({});
 * export const viewArns = example.then(example => .map(view => (view.arn)));
 * export const primaryViewArnByName = example.then(example => .filter(view => view.name == "Primary View").map(view => (view.arn))[0]);
 * ```
 */
function getViewsOutput(args, opts) {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:billing/getViews:getViews", {
        "billingViewTypes": args.billingViewTypes,
    }, opts);
}
exports.getViewsOutput = getViewsOutput;
//# sourceMappingURL=getViews.js.map