"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getConnectionOutput = exports.getConnection = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Fetches details of a Site-to-Site VPN connection. A Site-to-Site VPN connection is an Internet Protocol security (IPsec) VPN connection between a VPC and an on-premises network.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     filters: [{
 *         name: "customer-gateway-id",
 *         values: ["cgw-1234567890"],
 *     }],
 * });
 * export const vpnConnectionId = example.then(example => example.vpnConnectionId);
 * ```
 *
 * ### Find by VPN Connection ID
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     vpnConnectionId: "vpn-abcd1234567890",
 * });
 * export const gatewayAssociationState = example.then(example => example.gatewayAssociationState);
 * ```
 */
/** @deprecated aws.vpn/getconnection.getConnection has been deprecated in favor of aws.ec2/getvpnconnection.getVpnConnection */
function getConnection(args, opts) {
    pulumi.log.warn("getConnection is deprecated: aws.vpn/getconnection.getConnection has been deprecated in favor of aws.ec2/getvpnconnection.getVpnConnection");
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:vpn/getConnection:getConnection", {
        "filters": args.filters,
        "region": args.region,
        "vpnConnectionId": args.vpnConnectionId,
    }, opts);
}
exports.getConnection = getConnection;
/**
 * Fetches details of a Site-to-Site VPN connection. A Site-to-Site VPN connection is an Internet Protocol security (IPsec) VPN connection between a VPC and an on-premises network.
 *
 * ## Example Usage
 *
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     filters: [{
 *         name: "customer-gateway-id",
 *         values: ["cgw-1234567890"],
 *     }],
 * });
 * export const vpnConnectionId = example.then(example => example.vpnConnectionId);
 * ```
 *
 * ### Find by VPN Connection ID
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const example = aws.ec2.getVpnConnection({
 *     vpnConnectionId: "vpn-abcd1234567890",
 * });
 * export const gatewayAssociationState = example.then(example => example.gatewayAssociationState);
 * ```
 */
/** @deprecated aws.vpn/getconnection.getConnection has been deprecated in favor of aws.ec2/getvpnconnection.getVpnConnection */
function getConnectionOutput(args, opts) {
    pulumi.log.warn("getConnection is deprecated: aws.vpn/getconnection.getConnection has been deprecated in favor of aws.ec2/getvpnconnection.getVpnConnection");
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws:vpn/getConnection:getConnection", {
        "filters": args.filters,
        "region": args.region,
        "vpnConnectionId": args.vpnConnectionId,
    }, opts);
}
exports.getConnectionOutput = getConnectionOutput;
//# sourceMappingURL=getConnection.js.map